/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "The": "",
    " Scrap:": "废料：",
    ", is awarded for interrupting the equipment repair process by manually entering combat.": "，因手动进入战斗中断装备修复过程而获奖。",
    ", is awarded for reaching level 50 without providing custom names or descriptions for anything.": "，在未提供任何自定义名称或描述的情况下达到 50 级时获得奖励。",
    "(formerly Intuition)": "（以前的直觉）",
    "(formerly Patience and Discipline)": "（以前的耐心和纪律）",
    "(formerly Thorough Looting)": "（以前的彻底掠夺）",
    "(formerly Will To Live)": "（原《生存意志》）",
    "×": "×",
    "A (!) will appear on the combat tab when in combat.": "战斗时战斗选项卡上会出现一个（！）。",
    "A (!) will appear on the items tab if your inventory is full.": "如果您的库存已满，物品选项卡上将出现一个 (!)。",
    "A few of the special items have had their debuffs modified.": "一些特殊物品的减益效果已被修改。",
    "A new badge,": "新徽章，",
    "A new zone has been added.": "添加了一个新区域。",
    "Absorption Shield": "吸收护盾",
    "Adrenaline Rush": "肾上腺素",
    "Alchemist's Intuition": "炼金术士的直觉",
    "All badges relating to reaching maximum levels with specific skills have been removed, due to the introduction of the new skill tree.": "由于引入了新的技能树，所有与达到特定技能最高级别相关的徽章都已被删除。",
    "Ancestral Fortitude": "祖先的坚韧",
    "Armour Mastery": "护甲精通",
    "Artful Dodger": "狡猾的道奇",
    "Attack speed increase is now 3% per rank (up from 2%).": "攻击速度现在每等级提高 3%（原为 2%）。",
    "Badges": "徽章",
    "Balance Changes": "平衡变动",
    "Bartering": "物物交换",
    "Bladed Armour": "刃甲",
    "Bloodlust": "嗜血",
    "Bountiful Bags": "丰富的袋子",
    "Brewmaster": "酿酒大师",
    "by Psychemaster - Version 1.1": "由 Psychemaster - 版本 1.1",
    "Can now be purchased alongside Absorption Shield.": "现在可以与吸收护盾一起购买。",
    "Can now be purchased alongside Reflective Shield.": "现在可以与反光盾一起购买。",
    "Chance of an additional stat boost is now 2% per rank (down from 3%).": "现在，每等级获得额外统计提升的几率为 2%（低于 3%）。",
    "Chance to deliver a second attack is now 2% per rank (up from 1%).": "现在，每等级发动第二次攻击的几率为 2%（原为 1%）。",
    "Chance to gain an additional Stat Point is now 2% per rank (up from 1%).": "现在，获得额外统计点的几率为每等级 2%（原为 1%）。",
    "Changes in this version:": "该版本的变化：",
    "Click here to enter combat": "点击这里进入战斗",
    "Combat": "战斗",
    "Constitution": "体质",
    "Damage absorbed is now 20% per rank (down from 100%).": "吸收的伤害现在为每等级 20%（低于 100%）。",
    "Damage increase is now 3% per rank (up from 2%).": "现在每等级伤害增加 3%（原为 2%）。",
    "Damage increase is now 35% (up from 25%).": "伤害增加现在为 35%（原为 25%）。",
    "Damage increase is now 5% per rank (up from 4%).": "现在每等级伤害增加 5%（原为 4%）。",
    "Damage reduction is now 3% per rank (up from 2%).": "现在每等级伤害减少 3%（原为 2%）。",
    "Damage reflected is now 20% per rank (down from 100%).": "反射伤害现在为每等级 20%（低于 100%）。",
    "Deadly Force": "致命力量",
    "Deadly Momentum": "致命势头",
    "Debuff application rate increase is now 2% per rank (up from 1%).": "减益应用率现在每等级增加 2%（原为 1%）。",
    "Defense": "防御",
    "Dexterity": "灵巧",
    "Divine Shield": "圣盾",
    "Each rank provides a 1% chance to get scrap from a kill (down from 2%).": "每个等级都有 1% 的几率从击杀中获得废品（低于 2%）。",
    "Each rank provides a 3% chance to prevent durability loss (up from 2%).": "每个等级都有 3% 的机会防止耐久性损失（原为 2%）。",
    "Empowered Flurry": "强化乱舞",
    "Enemies no longer have a chance to generate with equipment of a higher level than they are.": "敌人不再有机会生成比自己等级更高的装备。",
    "Execute": "执行",
    "Expose Weakness": "暴露弱点",
    "Eye for an Eye": "以眼还眼",
    "Fast Learner": "快速学习者",
    "Five Finger Discount": "五指折扣",
    "Fixed an issue where Flurry could potentially activate from an attack that was prevented by paralysis.": "修复了乱舞可能会因麻痹所阻止的攻击而激活的问题。",
    "Fixed an issue where it was less likely to activate than intended.": "修复了激活可能性低于预期的问题。",
    "Fixed an issue where Press the Advantage would not activate when the player had no skill points in Wild Swings.": "修复了当玩家在狂野挥击中没有技能点时，按下优势不会激活的问题。",
    "Fixed an issue where the accumulated experience was not removed when prestiging.": "修复了声望时积累的经验没有被移除的问题。",
    "Fixed an issue where the badges 'Flawless Victory' and 'MC Hammer Special' would not be granted if all incoming attacks were negated via Divine Shield.": "修复了如果所有传入攻击都通过圣盾无效，则不会授予徽章“完美胜利”和“MC Hammer Special”的问题。",
    "Fixed an issue where the chance of randomly generating a 'Great' item was lower than it should have been.": "修复了随机生成“伟大”物品的机会低于应有的问题。",
    "Fixed an issue where the default debuff name was not being applied if the dialogue was left blank.": "修复了如果对话留空则不会应用默认减益名称的问题。",
    "Fixed an issue where the random debuff reforge could not select the 'Sleep' debuff.": "修复了随机减益重铸无法选择“睡眠”减益的问题。",
    "Fixed an issue where this skill was far less effective than intended.": "修复了该技能远不如预期有效的问题。",
    "Flurry": "乱舞",
    "Four new skills have been added that relate to potions.": "添加了四项与职位相关的新技能。",
    "Game loaded.": "游戏已加载。",
    "Generic Player Name (Lv. 1)": "通用玩家名称（Lv.1）",
    "gives a chance to block enemy attacks, reducing the damage taken by 25%;": "有一定几率格挡敌人的攻击，减少受到的伤害25%；",
    "gives a chance to critically strike enemies for 50% increased damage;": "有一定几率对敌人造成暴击，伤害提高 50%；",
    "gives a chance to dodge an incoming attack, preventing all effects of it;": "有机会躲避即将到来的攻击，防止其所有影响；",
    "gives a chance to restore health equal to your Constitution value when attacking.": "攻击时有一定几率恢复相当于你体质值的生命值。",
    "Good Enough for Me": "对我来说足够好",
    "Has been changed to increase the power of out of combat regeneration only.": "已更改为仅增加战斗外再生的力量。",
    "Health potions have a chance to drop scaling with the opponent's armour quality (Good or better).": "生命药水有机会降低对手护甲质量（好或更好）的缩放比例。",
    "Help": "帮助",
    "Hold the Line": "保持线路",
    "Hold The Line": "保持冷静",
    "HP: 115 / 115 (100%)": "生命值：115 / 115 (100%)",
    "If you already have a potion with a matching debuff, then getting one as a drop grants an additional 10 uses, with no upper limit.": "如果您已经拥有具有匹配减益效果的药水，那么以掉落形式获得一瓶即可额外获得 10 次使用，没有上限。",
    "Increased the bonus amount healed to 4% per rank (up from 2%).": "每个等级的治疗奖励金额从 2% 增加到 4%。",
    "Indicators will appear on the tab bar under certain circumstances:": "在某些情况下，标签栏上会出现指示器：",
    "Intelligence": "智力",
    "is a new 5 rank skill in the Defence tree, granting a 2% chance per rank to Disarm the attacker upon a successful block. Branches from": "是防御树中的新 5 技能，每级有 2% 的几率在成功格挡后解除攻击者的武装。",
    "is a new 5 rank skill in the Defence tree, granting a 2% chance per rank to ignore enemy armour bonuses. Branches from": "是防御树中的新 5 技能，每级有 2% 的几率忽略敌人的护甲等级加值。",
    "is a new 5 rank skill in the Defence tree, increasing block chance by 1% per rank. Branches from": "是防御树中的新 5 技能，每级增加 1% 的格挡几率。",
    "is a new 5 rank skill in the Defence tree, that deals a flat 2% per rank of damage taken to an attacker. Branches from": "是防御树中的一项新 5 技能，对攻击者造成的伤害每等级固定 2%。",
    "is a new 5 rank skill in the Defence tree, which will negate a killing blow made against you and restore 6% of your maximum health per rank, once per battle. Branches from": "是防御树中的一个新的 5 技能，它将抵消对你造成的致命一击，并在每场战斗中恢复你每等级最大生命值的 6%。",
    "is a new 5 rank skill in the Offense tree, which applies Adrenaline Rush at the start of combat for one attack per rank. Branches from": "是进攻树中的一项新 5 技能，它在战斗开始时应用肾上腺素冲刺，每级进行一次攻击。分支来自",
    "is a new 5 rank skill in the Offense tree, which stores overkill damage from all other sources (up to 20% per rank of target's max HP) and applies it at the start of combat. Branches from": "是进攻树中的新 5 技能，它存储来自所有其他来源的过度杀伤伤害（目标最大生命值每级最多 20%）并在战斗开始时应用。",
    "is a new 5 rank skill in the Support tree, which gives a 1% chance per rank to not consume a potion charge when used. Branches from": "是支持树中的新 5 技能，每等级有 1% 的几率在使用时不消耗药水等级费用。",
    "is a new 5 rank skill in the Support tree, which increases your inventory size by 4 slots per rank. Branches from": "是支持树中的新 5 技能，每级增加 4 个槽位的库存大小。分支等级从",
    "is a new single rank skill in the Defence tree, causing successful dodges to refresh the cooldown on your Burst Attack. Branches from": "是防御树中的一个新的单级技能，成功闪避可以刷新你的爆发攻击的冷却时间。来自的分支",
    "is a new single rank skill in the Defence tree, guaranteeing a block whenever Shield Crush activates. Branches from": "是防御树中的一个新的单级技能，保证每当盾牌粉碎激活时都会格挡。",
    "is a new single rank skill in the Defence tree, which deals 100% of blocked damage to the attacker upon a successful block. Branches from": "是防御树中新的单级技能，成功格挡后会对攻击者造成 100% 被格挡伤害。",
    "is a new single rank skill in the Defence tree, which removes the active debuff on you when Shield Crush activates. Branches from": "是防御树中的一项新单级技能，当护盾粉碎激活时，它会消除你身上的主动减益效果。",
    "is a new single rank skill in the Offense tree, allowing the player to refresh debuff timers if they are reapplied during their duration. Branches from": "是进攻树中的一个新的单级技能，允许玩家在持续时间内重新应用减益计时器时刷新减益计时器。",
    "is a new single rank skill in the Offense tree, which refreshes your Burst Attack cooldown upon a critical hit. Branches from": "是进攻树中的一个新的单级技能，它会在致命一击时刷新你的爆发攻击冷却时间。",
    "is a new single rank skill in the Support tree, which additively increases healing from potions by 10%. Branches from": "是支持树中的一项新的单级技能，可将药水的治疗效果加成 10%。",
    "is a new single rank skill in the Support tree, which additively increases the chance of receiving a potion drop by 5%. Branches from": "是支持树中的一项新的单级技能，它使获得药水掉落的几率额外增加 5%。",
    "is a new single rank skill in the Support tree, which causes debuff potions to apply the superior versions of their debuffs. Branches from": "是支持树中的一项新的单级技能，它会导致减益药水应用其减益的高级版本。",
    "is the new base skill in the Defence tree, increasing the potency of armour bonuses by 5% per rank (rounded up to the nearest point).": "是防御树中的新基础技能，每级将护甲加成的效力提高 5%（四舍五入到最接近的点）。",
    "Item shop has been restocked.": "物品商店已重新进货。",
    "Items": "物品",
    "Items in the Inventory tab can now be locked, which prevents them from being sold, scrapped or discarded - including via the 'Clean Inventory' function.": "现在可以锁定“库存”选项卡中的物品，以防止它们被出售、报废或丢弃 - 包括通过“清理库存”功能。",
    "Last Bastion": "最后的堡垒",
    "Luck of the Draw": "抽奖的运气",
    "Lucky Star": "幸运星",
    "Master Tinkerer": "修补匠大师",
    "Medic's Intuition": "医生的直觉",
    "Miscellaneous Changes": "杂项变更",
    "Name change only - effect remains the same.": "仅名称更改 - 效果保持不变。",
    "New players will now load into the Updates tab by default when playing for the first time.": "现在，新玩家第一次玩游戏时将默认加载到“更新”选项卡中。",
    "New Skills": "新技能",
    "Nimble Fingers": "灵活的手指",
    "Now has 5 ranks available (down from 10).": "现在有 5 个可用等级（从 10 个减少）。",
    "Now has 5 ranks available (up from 1).": "现在有 5 个可用等级（原来为 1 个）。",
    "Offense": "罪行",
    "Overcharge": "过度充电",
    "Pandemic": "大流行",
    "Patience Rewarded": "耐心得到回报",
    "Pick Clean": "挑选清洁",
    "Pickpocket": "扒手",
    "Player": "玩家",
    "Player health and experience bars are now visible across all tabs.": "现在，玩家的生命值和经验栏在所有选项卡中都可见。",
    "Player stats now provide an additional passive bonus, which scales with their value subject to diminishing returns:": "玩家统计数据现在提供额外的被动奖励，其价值随着收益递减而变化：",
    "Potions": "药水",
    "Potions have been added to the game.": "游戏中已添加药水。",
    "Power Surge": "电涌",
    "Press the Advantage": "按优势",
    "Price reduction is now 3% per rank (up from 2%).": "现在每个等级降价 3%（原为 2%）。",
    "Proper Care": "适当的照顾",
    "Realm of Decay": "王权衰退",
    "Reclaimed Knowledge": "回收知识",
    "Reflective Shield": "反射盾",
    "Renaming your character is now accomplished by clicking the existing name below the health bar.": "现在，通过单击生命值栏下方的现有名称即可完成对角色的重命名。",
    "Restrictions on purchasing certain skill combinations have been removed.": "购买某些技能组合的限制已被取消。",
    "Riposte": "还击",
    "Saboteur's Intuition": "破坏者的直觉",
    "Second Wind": "第二次风",
    "Seeds:": "种子：",
    "Shield Crush": "盾牌粉碎",
    "Shield Wall": "盾墙",
    "Skill Changes": "技能变更",
    "Skills": "技能",
    "Skills will now display their actual effects on the Skills tab, instead of showing the effect per rank.": "技能现在将在“技能”选项卡上显示其实际效果，而不是显示每个等级的效果。",
    "Stand Your Ground": "坚守阵地",
    "Store": "店铺",
    "Strength": "力量",
    "Support": "支持",
    "Survival Instincts": "生存本能",
    "Terminally Unimaginative": "极度缺乏想象力",
    "The automatic inventory management system now supports discarding items, as well as the existing sell/scrap/ignore options.": "自动库存管理系统现在支持丢弃物品以及现有的出售/报废/忽略选项。",
    "The availability of Skill Points has been changed: a minimum level of 5 is required, and they are only naturally gained on odd levels beyond that point.": "技能点的可用性已更改：最低等级要求为 5，只有在超过该点的奇数等级上才能自然获得技能点。",
    "The base from which enemy stat scaling is calculated has been increased slightly, for both normal and elite foes. This will be most noticeable at lower levels.": "对于普通敌人和精英敌人，计算敌人统计数据的基础略有增加。这在较低级别时最为明显。",
    "The following skills have been updated:": "以下技能已更新：",
    "The following tabs are now hidden until certain conditions are met:": "以下选项卡现在处于隐藏状态，直到满足某些条件：",
    "The game is now built in Angular, as opposed to raw JavaScript. As a result of this, there should no longer be issues with UI elements occasionally not responding to interactions.": "该游戏现在是用 Angular 构建的，而不是原始 JavaScript。因此，UI 元素偶尔不响应交互的问题应该不再存在。",
    "The inventory cleaning function will always ignore potions.": "库存清理功能将始终忽略药水。",
    "The inventory is now capped at a baseline of 30 slots, and is now a single unified collection instead of individual sections per item type.": "库存现在的上限为 30 个槽位的基线，并且现在是一个统一的集合，而不是每个项目类型的单独部分。",
    "The number of skill points to be spent will appear on the Skills tab, if any.": "要花费的技能点数将显示在“技能”选项卡上（如果有）。",
    "The number of stat points to be spent will appear on the Player tab, if any.": "要花费的统计点数将显示在“玩家”选项卡上（如果有）。",
    "The skill tree has been completely redefined and split into three broad sections:": "技能树已完全重新定义并分为三个主要部分：",
    "The Store will now carry two debuff potions, selected at random from the pool of debuffs. The cost of these potions scales with player level.": "商店现在将提供两种从减益池中随机选择的减益药水。这些药水的成本与玩家等级成正比。",
    "The Zones tab will no longer show the names of zones you have yet to unlock.": "“区域”选项卡将不再显示您尚未解锁的区域的名称。",
    "Toast notifications are now much smaller and cleaner, and have a clear 'dismiss' option.": "Toast 通知现在更小、更干净，并且有一个明确的“关闭”选项。",
    "tree focuses on quality of life upgrades that don't fit into either of the above trees.": "树专注于生活质量的升级，但不适合上述任何一棵树。",
    "tree focuses on skills that decrease damage taken and effects that occur when attacked;": "树专注于减少受到的伤害和受到攻击时发生的效果的技能；",
    "tree focuses on skills that increase damage done and effects that occur when attacking;": "树专注于增加攻击时造成的伤害和效果的技能；",
    "UI Changes": "用户界面的变化",
    "Undermine": "破坏",
    "Update News": "更新新闻",
    "Updated to restore 5% health per rank upon defeating an enemy.": "更新为在击败敌人时恢复每等级 5% 的生命值。",
    "Updates": "更新",
    "Version 1.1": "1.1版",
    "Victory Rush": "胜利冲刺",
    "When fighting an opponent whose weapon has a debuff, you have a chance (scaling with weapon quality) to receive a potion upon victory corresponding to that debuff.": "当与武器带有减益效果的对手战斗时，你有机会（与武器质量成比例）在胜利后获得与该减益效果相对应的药水。",
    "When in combat, clicking the enemy's name below the health bar will now initiate your Burst Attack.": "在战斗中，单击生命条下方的敌人名称现在将启动爆发攻击。",
    "When in combat, the experience bar will be replaced by the enemy's health bar.": "战斗时，经验条将被敌人的生命条取代。",
    "Wording has been updated to clarify that this skill only activates on levels you would normally gain skill points.": "措辞已更新，以澄清该技能仅在您通常会获得技能点的级别上激活。",
    "You start with a basic healing potion with 10 uses that restores 30% of your health when activated.": "你从基本治疗药水开始，使用 10 次，激活后可恢复 30% 的生命值。",
    "Zones": "区域",
    "- Begins repairing your equipment.": "- 开始修理你的设备。",
    "- Causes attacks against the victim to heal the attacker for a percentage of their health.": "- 对受害者进行攻击，以治愈攻击者一定比例的生命值。",
    "- Causes attacks against the victim to trigger a second instant hit for half the damage of the first.": "- 导致对受害者的攻击触发第二次即时攻击，伤害为第一次的一半。",
    "- Causes attacks to ignore any resistances on the victim's armour while active.": "- 使攻击在激活时忽略受害者盔甲上的任何阻力。",
    "- Causes the delay between the victim's attacks to increase.": "- 导致受害者攻击之间的延迟增加。",
    "- Causes the victim to fall asleep, preventing them from attacking. Can be broken prematurely by incoming attacks.": "- 使受害者入睡，防止他们攻击。可能会因传入的攻击而过早被破坏。",
    "- Causes the victim to lose a percentage of their health every second while active.": "- 导致受害者在活跃时每秒损失一定比例的生命值。",
    "- Causes the victim to use their fists or other appendages to attack instead of their weapon.": "- 导致受害者使用拳头或其他肢体而不是武器进行攻击。",
    "- Causes the victim's attacks to occasionally fail.": "- 导致受害者的攻击偶尔失败。",
    "- Causes the victim's next attack to be aimed at themselves.": "- 导致受害者的下一次攻击针对自己。",
    "- Enters combat, if it isn't already in progress.": "- 进入战斗（如果尚未进行）。",
    "- Flees from combat, if it is in progress.": "- 逃离战斗（如果战斗正在进行）。",
    "- Focuses the UI on the Badges tab.": "- 将 UI 集中在“徽章”选项卡上。",
    "- Focuses the UI on the Combat tab.": "- 将用户界面集中在“战斗”选项卡上。",
    "- Focuses the UI on the Help tab.": "- 将 UI 聚焦在“帮助”选项卡上。",
    "- Focuses the UI on the Items tab.": "- 将 UI 集中在“项目”选项卡上。",
    "- Focuses the UI on the Options tab.": "- 将 UI 聚焦在“选项”选项卡上。",
    "- Focuses the UI on the Player tab.": "- 将 UI 集中在“播放器”选项卡上。",
    "- Focuses the UI on the Skills tab.": "- 将 UI 集中在“技能”选项卡上。",
    "- Focuses the UI on the Store tab.": "- 将 UI 集中在“商店”选项卡上。",
    "- Focuses the UI on the Updates tab.": "- 将 UI 集中在“更新”选项卡上。",
    "- Focuses the UI on the Zones tab.": "- 将 UI 聚焦在“区域”选项卡上。",
    "- Save the game, if out of combat.": "- 如果脱离战斗，请保存游戏。",
    "- The victim has a chance to die instantly after a short duration, taking significant damage if they are not instantly killed.": "- 受害者有机会在短时间内死亡，如果没有立即死亡，则会受到严重伤害。",
    "- Triggers a Burst Attack when in combat.": "- 战斗时触发爆发攻击。",
    "A number of the game's functions are quickly and easily accessible via keyboard buttons. These are as follows:": "游戏的许多功能都可以通过键盘按钮快速轻松地访问，如下所示：",
    "Amazing": "惊人",
    "Armour pieces lose their positive protection stats - negative stats will still have an effect.": "盔甲部件失去了积极的保护统计数据 - 消极的统计数据仍然会产生影响。",
    "Armour Shred": "护甲碎片",
    "Badges are one-time awards for performing certain actions or meeting certain criteria as you play the game, and the Badges tab shows which ones are available and which ones are earned.": "徽章是您在玩游戏时执行某些操作或满足某些标准时获得的一次性奖励，“徽章”选项卡显示哪些徽章可用以及哪些徽章是已获得的。",
    "Bleed": "流血",
    "Confuse": "迷惑",
    "Debuffs": "减益效果",
    "Defence": "防御",
    "Disarm": "解除武装",
    "Doom": "厄运",
    "Drain": "流走",
    "Durability and Decay": "耐久性和腐烂",
    "During combat, these buttons are replaced with in-combat functions - the ability to flee, activate a burst attack, or use your equipped potion.": "在战斗中，这些按钮会被战斗中的功能所取代 - 逃跑、激活爆发攻击或使用装备的药水的能力。",
    "Each badge earned increases experience and seeds gained from combat by 2%, after all other effects and modifiers.": "扣除所有其他效果和修饰符后，获得的每个徽章都会使战斗中获得的经验和种子增加 2%。",
    "Each stat, in addition to having a direct effect, has a secondary effect that scales with its' value, subject to diminishing returns.": "每个统计数据除了具有直接影响外，还具有与其值成比例的次要影响，但收益递减。",
    "Each zone has a level range, which dictates the power of monsters that can be found there, as well as the items you can purchase from the store.": "每个区域都有一个等级范围，这决定了在那里可以找到的怪物的力量，以及您可以从商店购买的物品。",
    "Equipped items can be repaired. While the repair function is running, you may change your equipment at will - the function stops once all currently equipped items are repaired.": "装备的物品可以进行修复，修复功能运行期间，你可以随意更换装备，一旦当前装备的物品全部修复完毕，该功能就会停止。",
    "Equipped items will become damaged as they are used - the amount of durability they can have scales with their level.": "装备好的物品会在使用时受到损坏——它们的耐久度会随着等级的变化而变化。",
    "Good": "好的",
    "Great": "伟大的",
    "Higher quality weapons can possess one of ten unique debuffs, which activate to assist in combat. These are as follows:": "更高质量的武器可以拥有十种独特的减益效果之一，这些减益效果可以激活以协助战斗。这些减益效果如下：",
    "If you win, you are given the enemy's equipped items, some experience and some seeds. If you lose, you'll be penalised a percentage of the experience you have on hand.": "如果你赢了，你会得到敌人的装备、一些经验和一些种子；如果你输了，你会受到你手头经验的一定比例的惩罚。",
    "Information about the last major game update appears in the Updates tab.": "有关上次主要游戏更新的信息显示在“更新”选项卡中。",
    "It takes care of most of the game's core loop - the fighting, repairing and selling of items, leaving the player to make other decisions.": "它负责游戏的大部分核心循环——战斗、修理和销售物品，让玩家做出其他决定。",
    "It won't change your equipment, make purchases on your behalf, spend stat or skill points, or attempt to fight area bosses.": "它不会改变你的装备、代表你进行购买、花费统计数据或技能点，或尝试与区域首领战斗。",
    "Item Quality": "物品质量",
    "Items can be discarded, for when you just don't care about them.": "当您不关心物品时，可以丢弃它们。",
    "Items can be equipped at any time (even during battles), which is useful to know if you need a change of tack for a given encounter.": "可以随时装备物品（甚至在战斗中），这对于了解您是否需要针对特定​​遭遇改变策略很有用。",
    "Items can be locked, which prevents all actions against them other than equipping them - this includes the inventory cleaning function.": "物品可以被锁定，这可以防止除装备物品之外的所有针对物品的操作 - 这包括库存清理功能。",
    "Items can be scrapped, which provides the scrap you need for other upgrades and modifications.": "物品可以报废，这为您提供其他升级和修改所需的报废。",
    "Items can be sold for seeds, which are then used to buy new items in the store or upgrade existing ones.": "物品可以出售为种子，然后用于在商店购买新物品或升级现有物品。",
    "Items in the game can be generated with one of 5 quality levels (in order of least to most powerful):": "游戏中的物品可以以 5 个质量级别之一生成（按照从最弱到最强大的顺序）：",
    "Keybindings": "键绑定",
    "Multistrike": "多重打击",
    "Normal": "普通的",
    "Offence": "罪行",
    "Paralysis": "麻痹",
    "Poor": "贫穷的",
    "Repairing items is free, only taking time. The speed of repairing items scales with your level. You may end the repairing state early by entering combat.": "修复物品是免费的，只需要时间。修复物品的速度与你的等级成正比。你可以通过进入战斗提前结束修复状态。",
    "Resetting stats costs some scrap, with the cost scaling with the number of stat points spent.": "重置统计数据会产生一些废品，成本随着消耗的统计点数的增加而增加。",
    "Since the level of items generated in the store is capped based on your current level and the zone level, moving to the highest zone you can reach ensures that store items are the best they can be.": "由于商店中生成的物品等级根据您当前的等级和区域等级而受到限制，因此移动到您可以到达的最高区域可确保商店物品达到最佳状态。",
    "Skills that are not yet available to upgrade will be faded out - these will open up as you raise existing skills to their maximum level.": "尚未可升级的技能将逐渐消失 - 当您将现有技能提升到最高水平时，这些技能将会开放。",
    "Sleep": "睡眠",
    "Slow": "慢",
    "Spend scrap to apply a new debuff to an existing weapon of Good quality or better.": "花费废料对优质或更好品质的现有武器应用新的减益效果。",
    "Spend scrap to upgrade your equipment's quality, which makes its' stats scale better with levels and sometimes adds new effects.": "花费废料来升级你的装备的质量，这使得它的统计数据随着等级的增加而更好，有时还会增加新的效果。",
    "Spend seeds to acquire new equipment and potions.": "花费种子来购买新设备和药水。",
    "Spend seeds to upgrade your equipment's level, improving its' stats.": "花费种子来升级你的装备等级，提高其属性。",
    "The 'Clean Inventory' button will process all unlocked items you are currently carrying, performing a specific action on each one based on choices made on the Options tab.": "“清理库存”按钮将处理您当前携带的所有未锁定物品，并根据“选项”选项卡上所做的选择对每件物品执行特定操作。",
    "The 'Save Game' and 'Reset Game' buttons are, hopefully, self-explanatory - but they have a note attached to them just in case!": "希望“保存游戏”和“重置游戏”按钮是不言自明的 - 但它们附有注释以防万一！",
    "The Auto-battle system is what makes the game semi-idle.": "自动战斗系统使游戏变得半空闲。",
    "The auto-battle system uses this function as part of its' operation, and will in fact halt if the inventory remains full once this function has been triggered.": "自动战斗系统使用此功能作为其操作的一部分，并且一旦触发此功能，如果库存仍然满，实际上会停止。",
    "The burst attack is an instant strike delivered with your equipped weapon, with a base cooldown of 10 seconds.": "爆发攻击是用你所装备的武器进行的即时攻击，基本冷却时间为 10 秒。",
    "The combat tab plays host to the combat log, and functions related to combat.": "战斗选项卡负责战斗日志以及与战斗相关的功能。",
    "The Constitution stat has a chance to gain two points on level up instead of one.": "体质属性有机会在升级时获得两点而不是一点。",
    "The controls here determine what happens to each item type and quality when that button is pressed.": "这里的控件决定按下该按钮时每个项目类型和质量会发生什么。",
    "The game features a total of fourteen different zones, accessible via the Zones tab once you defeat your first area boss.": "该游戏共有十四个不同的区域，一旦您击败第一个区域老板，就可以通过“区域”选项卡访问。",
    "The game's three skill trees become available once you have earned your first skill point at level 5, and points are earned every other level afterwards.": "一旦您在第 5 级获得第一个技能点，游戏的三个技能树就会变得可用，之后每隔一个级别都会获得积分。",
    "The inventory cleaning function makes item management easier, by running a bulk operation when you click the button on the Items tab.": "库存清理功能通过单击“项目”选项卡上的按钮运行批量操作，使项目管理变得更加容易。",
    "The Items tab lists all of your currently held items, and provides various options for what you can do with them:": "“项目”选项卡列出了您当前持有的所有项目，并提供了各种选项来说明您可以使用它们执行哪些操作：",
    "The options tab provides controls for some of the game's systems:": "选项选项卡提供了一些游戏系统的控件：",
    "The Player tab holds your stats and the panel which allows you to assign stat points.": "“玩家”选项卡包含您的统计数据和允许您分配统计点的面板。",
    "The shop will periodically restock, and a manual restock can be forced by moving between zones if you have more than one available.": "商店会定期补货，如果您有多个可用区域，则可以通过在区域之间移动来强制手动补货。",
    "The Skills tab lets you interact with the skill trees once it becomes available. Skill points can be moved at will between skills at any time, even in combat.": "一旦技能树可用，“技能”选项卡可让您与技能树进行交互。技能点可以随时在技能之间随意移动，甚至在战斗中也是如此。",
    "The Store tab is your one-stop shop for acquiring new equipment, as well as upgrading existing pieces that you wish to keep. It has the following functions:": "商店选项卡是您获取新装备以及升级您想要保留的现有装备的一站式商店。它具有以下功能：",
    "This function will not touch Potions, regardless of locked status.": "无论锁定状态如何，此功能都不会触及药水。",
    "tree focuses on effects that don't fit into either of the other trees, such as boosted resource gains or experience.": "树专注于不适合其他树的效果，例如增加资源增益或经验。",
    "tree focuses on effects that increase damage dealt to enemies, and effects that occur when attacking.": "树专注于增加对敌人造成的伤害的效果，以及攻击时发生的效果。",
    "tree focuses on effects that reduce damage taken from enemies, and effects that occur when attacked.": "树专注于减少敌人造成的伤害的效果，以及受到攻击时发生的效果。",
    "Upon entering combat, both combatants will trade blows until one of them emerges victorious.": "进入战斗后，双方将互相攻击，直到其中一方取得胜利。",
    "Weapons have their damage values halved, and no longer apply their debuffs.": "武器的伤害值减半，并且不再施加减益效果。",
    "When an item reaches zero durability, it breaks, losing some of its' functionality:": "当一个物品的耐用性达到零时，它就会损坏，失去一些功能：",
    "When leveling up, you gain one point in each stat, plus another point in the stat that relates to your equipped weapon, as well as an additional stat point to spend freely.": "升级时，您在每个统计数据中获得一分，再加上与您所装备的武器相关的统计数据中的另一点，以及可自由花费的额外统计点。",
    "While a sixth quality level does exist, it is not attainable by players, and is used entirely for equipment held by area bosses.": "虽然第六品质等级确实存在，但玩家无法达到，并且完全用于区域首领持有的装备。",
    "While not in combat, there are buttons here to repair equipment, look for a fight, or engage the area boss once you've reached the level cap for the zone.": "当不在战斗中时，这里有一些按钮可以修复装备、寻找战斗，或者在达到该区域的等级上限后与区域首领交战。",
    "+Max": "+最大",
    "Gives a 4.68% to restore 6 HP when attacking.": "攻击时有 4.68% 恢复 6 点生命值。",
    "Increases chance to block attacks by 5.15%.": "格挡攻击的几率增加 5.15%。",
    "Increases chance to critically strike by 4.18%.": "暴击率增加 4.18%。",
    "Increases chance to dodge attacks by 2.58%.": "躲避攻击的几率增加 2.58%。",
    "Increases damage dealt with magic weapons.": "增加魔法武器造成的伤害。",
    "Increases damage dealt with melee weapons.": "增加近战武器造成的伤害。",
    "Increases damage dealt with ranged weapons.": "增加远程武器造成的伤害。",
    "Increases maximum health and health restored when idle.": "增加最大生命值和闲置时恢复的生命值。",
    "Reset Your Stats": "重置您的属性点",
    "Stat Point Allocation": "属性点分配",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "EXP: ": "经验值：",
    "Strength (": "力量 (",
    "Intelligence (": "智力 (",
    "Dexterity (": "灵巧 (",
    "Constitution (": "体质 (",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) point free$/, '$1 免费点数'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);