/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "The": "",
    " Scrap:": "废料：",
    ", is awarded for interrupting the equipment repair process by manually entering combat.": "，因手动进入战斗中断装备修复过程而获奖。",
    ", is awarded for reaching level 50 without providing custom names or descriptions for anything.": "，在未提供任何自定义名称或描述的情况下达到 50 级时获得奖励。",
    "(formerly Intuition)": "（以前的直觉）",
    "(formerly Patience and Discipline)": "（以前的耐心和纪律）",
    "(formerly Thorough Looting)": "（以前的彻底掠夺）",
    "(formerly Will To Live)": "（原《生存意志》）",
    "×": "×",
    "A (!) will appear on the combat tab when in combat.": "战斗时战斗选项卡上会出现一个（！）。",
    "A (!) will appear on the items tab if your inventory is full.": "如果您的库存已满，物品选项卡上将出现一个 (!)。",
    "A few of the special items have had their debuffs modified.": "一些特殊物品的减益效果已被修改。",
    "A new badge,": "新徽章，",
    "A new zone has been added.": "添加了一个新区域。",
    "Absorption Shield": "吸收护盾",
    "Adrenaline Rush": "肾上腺素",
    "Alchemist's Intuition": "炼金术士的直觉",
    "All badges relating to reaching maximum levels with specific skills have been removed, due to the introduction of the new skill tree.": "由于引入了新的技能树，所有与达到特定技能最高级别相关的徽章都已被删除。",
    "Ancestral Fortitude": "祖先的坚韧",
    "Armour Mastery": "护甲精通",
    "Artful Dodger": "狡猾的道奇",
    "Attack speed increase is now 3% per rank (up from 2%).": "攻击速度现在每等级提高 3%（原为 2%）。",
    "Badges": "徽章",
    "Balance Changes": "平衡变动",
    "Bartering": "物物交换",
    "Bladed Armour": "刃甲",
    "Bloodlust": "嗜血",
    "Bountiful Bags": "丰富的袋子",
    "Brewmaster": "酿酒大师",
    "by Psychemaster - Version 1.1": "由 Psychemaster - 版本 1.1",
    "Can now be purchased alongside Absorption Shield.": "现在可以与吸收护盾一起购买。",
    "Can now be purchased alongside Reflective Shield.": "现在可以与反光盾一起购买。",
    "Chance of an additional stat boost is now 2% per rank (down from 3%).": "现在，每等级获得额外统计提升的几率为 2%（低于 3%）。",
    "Chance to deliver a second attack is now 2% per rank (up from 1%).": "现在，每等级发动第二次攻击的几率为 2%（原为 1%）。",
    "Chance to gain an additional Stat Point is now 2% per rank (up from 1%).": "现在，获得额外属性点的几率为每等级 2%（原为 1%）。",
    "Changes in this version:": "该版本的变化：",
    "Click here to enter combat": "点击这里进入战斗",
    "Combat": "战斗",
    "Constitution": "体质",
    "Damage absorbed is now 20% per rank (down from 100%).": "吸收的伤害现在为每等级 20%（低于 100%）。",
    "Damage increase is now 3% per rank (up from 2%).": "现在每等级伤害增加 3%（原为 2%）。",
    "Damage increase is now 35% (up from 25%).": "伤害增加现在为 35%（原为 25%）。",
    "Damage increase is now 5% per rank (up from 4%).": "现在每等级伤害增加 5%（原为 4%）。",
    "Damage reduction is now 3% per rank (up from 2%).": "现在每等级伤害减少 3%（原为 2%）。",
    "Damage reflected is now 20% per rank (down from 100%).": "反射伤害现在为每等级 20%（低于 100%）。",
    "Deadly Force": "致命力量",
    "Deadly Momentum": "致命势头",
    "Debuff application rate increase is now 2% per rank (up from 1%).": "减益应用率现在每等级增加 2%（原为 1%）。",
    "Defense": "防御",
    "Dexterity": "灵巧",
    "Divine Shield": "圣盾",
    "Each rank provides a 1% chance to get scrap from a kill (down from 2%).": "每个等级都有 1% 的几率从击杀中获得废品（低于 2%）。",
    "Each rank provides a 3% chance to prevent durability loss (up from 2%).": "每个等级都有 3% 的机会防止耐久性损失（原为 2%）。",
    "Empowered Flurry": "强化乱舞",
    "Enemies no longer have a chance to generate with equipment of a higher level than they are.": "敌人不再有机会生成比自己等级更高的装备。",
    "Execute": "执行",
    "Expose Weakness": "暴露弱点",
    "Eye for an Eye": "以眼还眼",
    "Fast Learner": "快速学习者",
    "Five Finger Discount": "五指折扣",
    "Fixed an issue where Flurry could potentially activate from an attack that was prevented by paralysis.": "修复了乱舞可能会因麻痹所阻止的攻击而激活的问题。",
    "Fixed an issue where it was less likely to activate than intended.": "修复了激活可能性低于预期的问题。",
    "Fixed an issue where Press the Advantage would not activate when the player had no skill points in Wild Swings.": "修复了当玩家在狂野挥击中没有技能点时，按下优势不会激活的问题。",
    "Fixed an issue where the accumulated experience was not removed when prestiging.": "修复了声望时积累的经验没有被移除的问题。",
    "Fixed an issue where the badges 'Flawless Victory' and 'MC Hammer Special' would not be granted if all incoming attacks were negated via Divine Shield.": "修复了如果所有传入攻击都通过圣盾无效，则不会授予徽章“完美胜利”和“MC Hammer Special”的问题。",
    "Fixed an issue where the chance of randomly generating a 'Great' item was lower than it should have been.": "修复了随机生成“伟大”物品的机会低于应有的问题。",
    "Fixed an issue where the default debuff name was not being applied if the dialogue was left blank.": "修复了如果对话留空则不会应用默认减益名称的问题。",
    "Fixed an issue where the random debuff reforge could not select the 'Sleep' debuff.": "修复了随机减益重铸无法选择“睡眠”减益的问题。",
    "Fixed an issue where this skill was far less effective than intended.": "修复了该技能远不如预期有效的问题。",
    "Flurry": "乱舞",
    "Four new skills have been added that relate to potions.": "添加了四项与职位相关的新技能。",
    "Game loaded.": "游戏已加载。",
    "Generic Player Name (Lv. 1)": "通用玩家名称（Lv.1）",
    "gives a chance to block enemy attacks, reducing the damage taken by 25%;": "有一定几率格挡敌人的攻击，减少受到的伤害25%；",
    "gives a chance to critically strike enemies for 50% increased damage;": "有一定几率对敌人造成暴击，伤害提高 50%；",
    "gives a chance to dodge an incoming attack, preventing all effects of it;": "有机会躲避即将到来的攻击，防止其所有影响；",
    "gives a chance to restore health equal to your Constitution value when attacking.": "攻击时有一定几率恢复相当于你体质值的生命值。",
    "Good Enough for Me": "对我来说足够好",
    "Has been changed to increase the power of out of combat regeneration only.": "已更改为仅增加战斗外再生的力量。",
    "Health potions have a chance to drop scaling with the opponent's armour quality (Good or better).": "生命药水有机会降低对手护甲质量（好或更好）的缩放比例。",
    "Help": "帮助",
    "Hold the Line": "保持线路",
    "Hold The Line": "保持冷静",
    "HP: 115 / 115 (100%)": "生命值：115 / 115 (100%)",
    "If you already have a potion with a matching debuff, then getting one as a drop grants an additional 10 uses, with no upper limit.": "如果您已经拥有具有匹配减益效果的药水，那么以掉落形式获得一瓶即可额外获得 10 次使用，没有上限。",
    "Increased the bonus amount healed to 4% per rank (up from 2%).": "每个等级的治疗奖励金额从 2% 增加到 4%。",
    "Indicators will appear on the tab bar under certain circumstances:": "在某些情况下，标签栏上会出现指示器：",
    "Intelligence": "智力",
    "is a new 5 rank skill in the Defence tree, granting a 2% chance per rank to Disarm the attacker upon a successful block. Branches from": "是防御树中的新 5 技能，每级有 2% 的几率在成功格挡后解除攻击者的武装。",
    "is a new 5 rank skill in the Defence tree, granting a 2% chance per rank to ignore enemy armour bonuses. Branches from": "是防御树中的新 5 技能，每级有 2% 的几率忽略敌人的护甲等级加值。",
    "is a new 5 rank skill in the Defence tree, increasing block chance by 1% per rank. Branches from": "是防御树中的新 5 技能，每级增加 1% 的格挡几率。",
    "is a new 5 rank skill in the Defence tree, that deals a flat 2% per rank of damage taken to an attacker. Branches from": "是防御树中的一项新 5 技能，对攻击者造成的伤害每等级固定 2%。",
    "is a new 5 rank skill in the Defence tree, which will negate a killing blow made against you and restore 6% of your maximum health per rank, once per battle. Branches from": "是防御树中的一个新的 5 技能，它将抵消对你造成的致命一击，并在每场战斗中恢复你每等级最大生命值的 6%。",
    "is a new 5 rank skill in the Offense tree, which applies Adrenaline Rush at the start of combat for one attack per rank. Branches from": "是进攻树中的一项新 5 技能，它在战斗开始时应用肾上腺素冲刺，每级进行一次攻击。分支来自",
    "is a new 5 rank skill in the Offense tree, which stores overkill damage from all other sources (up to 20% per rank of target's max HP) and applies it at the start of combat. Branches from": "是进攻树中的新 5 技能，它存储来自所有其他来源的过度杀伤伤害（目标最大生命值每级最多 20%）并在战斗开始时应用。",
    "is a new 5 rank skill in the Support tree, which gives a 1% chance per rank to not consume a potion charge when used. Branches from": "是支持树中的新 5 技能，每等级有 1% 的几率在使用时不消耗药水等级费用。",
    "is a new 5 rank skill in the Support tree, which increases your inventory size by 4 slots per rank. Branches from": "是支持树中的新 5 技能，每级增加 4 个槽位的库存大小。分支等级从",
    "is a new single rank skill in the Defence tree, causing successful dodges to refresh the cooldown on your Burst Attack. Branches from": "是防御树中的一个新的单级技能，成功闪避可以刷新你的爆发攻击的冷却时间。来自的分支",
    "is a new single rank skill in the Defence tree, guaranteeing a block whenever Shield Crush activates. Branches from": "是防御树中的一个新的单级技能，保证每当盾牌粉碎激活时都会格挡。",
    "is a new single rank skill in the Defence tree, which deals 100% of blocked damage to the attacker upon a successful block. Branches from": "是防御树中新的单级技能，成功格挡后会对攻击者造成 100% 被格挡伤害。",
    "is a new single rank skill in the Defence tree, which removes the active debuff on you when Shield Crush activates. Branches from": "是防御树中的一项新单级技能，当护盾粉碎激活时，它会消除你身上的主动减益效果。",
    "is a new single rank skill in the Offense tree, allowing the player to refresh debuff timers if they are reapplied during their duration. Branches from": "是进攻树中的一个新的单级技能，允许玩家在持续时间内重新应用减益计时器时刷新减益计时器。",
    "is a new single rank skill in the Offense tree, which refreshes your Burst Attack cooldown upon a critical hit. Branches from": "是进攻树中的一个新的单级技能，它会在致命一击时刷新你的爆发攻击冷却时间。",
    "is a new single rank skill in the Support tree, which additively increases healing from potions by 10%. Branches from": "是支持树中的一项新的单级技能，可将药水的治疗效果加成 10%。",
    "is a new single rank skill in the Support tree, which additively increases the chance of receiving a potion drop by 5%. Branches from": "是支持树中的一项新的单级技能，它使获得药水掉落的几率额外增加 5%。",
    "is a new single rank skill in the Support tree, which causes debuff potions to apply the superior versions of their debuffs. Branches from": "是支持树中的一项新的单级技能，它会导致减益药水应用其减益的高级版本。",
    "is the new base skill in the Defence tree, increasing the potency of armour bonuses by 5% per rank (rounded up to the nearest point).": "是防御树中的新基础技能，每级将护甲加成的效力提高 5%（四舍五入到最接近的点）。",
    "Item shop has been restocked.": "物品商店已重新进货。",
    "Items": "物品",
    "Items in the Inventory tab can now be locked, which prevents them from being sold, scrapped or discarded - including via the 'Clean Inventory' function.": "现在可以锁定“库存”选项卡中的物品，以防止它们被出售、报废或丢弃 - 包括通过“清理库存”功能。",
    "Last Bastion": "最后的堡垒",
    "Luck of the Draw": "抽奖的运气",
    "Lucky Star": "幸运星",
    "Master Tinkerer": "修补匠大师",
    "Medic's Intuition": "医生的直觉",
    "Miscellaneous Changes": "杂项变更",
    "Name change only - effect remains the same.": "仅名称更改 - 效果保持不变。",
    "New players will now load into the Updates tab by default when playing for the first time.": "现在，新玩家第一次玩游戏时将默认加载到“更新”选项卡中。",
    "New Skills": "新技能",
    "Nimble Fingers": "灵活的手指",
    "Now has 5 ranks available (down from 10).": "现在有 5 个可用等级（从 10 个减少）。",
    "Now has 5 ranks available (up from 1).": "现在有 5 个可用等级（原来为 1 个）。",
    "Offense": "罪行",
    "Overcharge": "过度充电",
    "Pandemic": "大流行",
    "Patience Rewarded": "耐心得到回报",
    "Pick Clean": "挑选清洁",
    "Pickpocket": "扒手",
    "Player": "玩家",
    "Player health and experience bars are now visible across all tabs.": "现在，玩家的生命值和经验栏在所有选项卡中都可见。",
    "Player stats now provide an additional passive bonus, which scales with their value subject to diminishing returns:": "玩家统计数据现在提供额外的被动奖励，其价值随着收益递减而变化：",
    "Potions": "药水",
    "Potions have been added to the game.": "游戏中已添加药水。",
    "Power Surge": "电涌",
    "Press the Advantage": "按优势",
    "Price reduction is now 3% per rank (up from 2%).": "现在每个等级降价 3%（原为 2%）。",
    "Proper Care": "适当的照顾",
    "Realm of Decay": "王权衰退",
    "Reclaimed Knowledge": "回收知识",
    "Reflective Shield": "反射盾",
    "Renaming your character is now accomplished by clicking the existing name below the health bar.": "现在，通过单击生命值栏下方的现有名称即可完成对角色的重命名。",
    "Restrictions on purchasing certain skill combinations have been removed.": "购买某些技能组合的限制已被取消。",
    "Riposte": "还击",
    "Saboteur's Intuition": "破坏者的直觉",
    "Second Wind": "第二次风",
    "Seeds:": "种子：",
    "Shield Crush": "盾牌粉碎",
    "Shield Wall": "盾墙",
    "Skill Changes": "技能变更",
    "Skills": "技能",
    "Skills will now display their actual effects on the Skills tab, instead of showing the effect per rank.": "技能现在将在“技能”选项卡上显示其实际效果，而不是显示每个等级的效果。",
    "Stand Your Ground": "坚守阵地",
    "Store": "商店",
    "Strength": "力量",
    "Support": "支持",
    "Survival Instincts": "生存本能",
    "Terminally Unimaginative": "极度缺乏想象力",
    "The automatic inventory management system now supports discarding items, as well as the existing sell/scrap/ignore options.": "自动库存管理系统现在支持丢弃物品以及现有的出售/报废/忽略选项。",
    "The availability of Skill Points has been changed: a minimum level of 5 is required, and they are only naturally gained on odd levels beyond that point.": "技能点的可用性已更改：最低等级要求为 5，只有在超过该点的奇数等级上才能自然获得技能点。",
    "The base from which enemy stat scaling is calculated has been increased slightly, for both normal and elite foes. This will be most noticeable at lower levels.": "对于普通敌人和精英敌人，计算敌人统计数据的基础略有增加。这在较低级别时最为明显。",
    "The following skills have been updated:": "以下技能已更新：",
    "The following tabs are now hidden until certain conditions are met:": "以下选项卡现在处于隐藏状态，直到满足某些条件：",
    "The game is now built in Angular, as opposed to raw JavaScript. As a result of this, there should no longer be issues with UI elements occasionally not responding to interactions.": "该游戏现在是用 Angular 构建的，而不是原始 JavaScript。因此，UI 元素偶尔不响应交互的问题应该不再存在。",
    "The inventory cleaning function will always ignore potions.": "库存清理功能将始终忽略药水。",
    "The inventory is now capped at a baseline of 30 slots, and is now a single unified collection instead of individual sections per item type.": "库存现在的上限为 30 个槽位的基线，并且现在是一个统一的集合，而不是每个项目类型的单独部分。",
    "The number of skill points to be spent will appear on the Skills tab, if any.": "要花费的技能点数将显示在“技能”选项卡上（如果有）。",
    "The number of stat points to be spent will appear on the Player tab, if any.": "要花费的属性点数将显示在“玩家”选项卡上（如果有）。",
    "The skill tree has been completely redefined and split into three broad sections:": "技能树已完全重新定义并分为三个主要部分：",
    "The Store will now carry two debuff potions, selected at random from the pool of debuffs. The cost of these potions scales with player level.": "商店现在将提供两种从减益池中随机选择的减益药水。这些药水的成本与玩家等级成正比。",
    "The Zones tab will no longer show the names of zones you have yet to unlock.": "“区域”选项卡将不再显示您尚未解锁的区域的名称。",
    "Toast notifications are now much smaller and cleaner, and have a clear 'dismiss' option.": "Toast 通知现在更小、更干净，并且有一个明确的“关闭”选项。",
    "tree focuses on quality of life upgrades that don't fit into either of the above trees.": "树专注于生活质量的升级，但不适合上述任何一棵树。",
    "tree focuses on skills that decrease damage taken and effects that occur when attacked;": "树专注于减少受到的伤害和受到攻击时发生的效果的技能；",
    "tree focuses on skills that increase damage done and effects that occur when attacking;": "树专注于增加攻击时造成的伤害和效果的技能；",
    "UI Changes": "用户界面的变化",
    "Undermine": "破坏",
    "Update News": "更新新闻",
    "Updated to restore 5% health per rank upon defeating an enemy.": "更新为在击败敌人时恢复每等级 5% 的生命值。",
    "Updates": "更新",
    "Version 1.1": "1.1版",
    "Victory Rush": "胜利冲刺",
    "When fighting an opponent whose weapon has a debuff, you have a chance (scaling with weapon quality) to receive a potion upon victory corresponding to that debuff.": "当与武器带有减益效果的对手战斗时，你有机会（与武器质量成比例）在胜利后获得与该减益效果相对应的药水。",
    "When in combat, clicking the enemy's name below the health bar will now initiate your Burst Attack.": "在战斗中，单击生命条下方的敌人名称现在将启动爆发攻击。",
    "When in combat, the experience bar will be replaced by the enemy's health bar.": "战斗时，经验条将被敌人的生命条取代。",
    "Wording has been updated to clarify that this skill only activates on levels you would normally gain skill points.": "措辞已更新，以澄清该技能仅在您通常会获得技能点的级别上激活。",
    "You start with a basic healing potion with 10 uses that restores 30% of your health when activated.": "你从基本治疗药水开始，使用 10 次，激活后可恢复 30% 的生命值。",
    "Zones": "区域",
    "- Begins repairing your equipment.": "- 开始修理你的设备。",
    "- Causes attacks against the victim to heal the attacker for a percentage of their health.": "- 对受害者进行攻击，以治愈攻击者一定比例的生命值。",
    "- Causes attacks against the victim to trigger a second instant hit for half the damage of the first.": "- 导致对受害者的攻击触发第二次即时攻击，伤害为第一次的一半。",
    "- Causes attacks to ignore any resistances on the victim's armour while active.": "- 使攻击在激活时忽略受害者盔甲上的任何阻力。",
    "- Causes the delay between the victim's attacks to increase.": "- 导致受害者攻击之间的延迟增加。",
    "- Causes the victim to fall asleep, preventing them from attacking. Can be broken prematurely by incoming attacks.": "- 使受害者入睡，防止他们攻击。可能会因传入的攻击而过早被破坏。",
    "- Causes the victim to lose a percentage of their health every second while active.": "- 导致受害者在活跃时每秒损失一定比例的生命值。",
    "- Causes the victim to use their fists or other appendages to attack instead of their weapon.": "- 导致受害者使用拳头或其他肢体而不是武器进行攻击。",
    "- Causes the victim's attacks to occasionally fail.": "- 导致受害者的攻击偶尔失败。",
    "- Causes the victim's next attack to be aimed at themselves.": "- 导致受害者的下一次攻击针对自己。",
    "- Enters combat, if it isn't already in progress.": "- 进入战斗（如果尚未进行）。",
    "- Flees from combat, if it is in progress.": "- 逃离战斗（如果战斗正在进行）。",
    "- Focuses the UI on the Badges tab.": "- 将 UI 集中在“徽章”选项卡上。",
    "- Focuses the UI on the Combat tab.": "- 将用户界面集中在“战斗”选项卡上。",
    "- Focuses the UI on the Help tab.": "- 将 UI 聚焦在“帮助”选项卡上。",
    "- Focuses the UI on the Items tab.": "- 将 UI 集中在“项目”选项卡上。",
    "- Focuses the UI on the Options tab.": "- 将 UI 聚焦在“选项”选项卡上。",
    "- Focuses the UI on the Player tab.": "- 将 UI 集中在“播放器”选项卡上。",
    "- Focuses the UI on the Skills tab.": "- 将 UI 集中在“技能”选项卡上。",
    "- Focuses the UI on the Store tab.": "- 将 UI 集中在“商店”选项卡上。",
    "- Focuses the UI on the Updates tab.": "- 将 UI 集中在“更新”选项卡上。",
    "- Focuses the UI on the Zones tab.": "- 将 UI 聚焦在“区域”选项卡上。",
    "- Save the game, if out of combat.": "- 如果脱离战斗，请保存游戏。",
    "- The victim has a chance to die instantly after a short duration, taking significant damage if they are not instantly killed.": "- 受害者有机会在短时间内死亡，如果没有立即死亡，则会受到严重伤害。",
    "- Triggers a Burst Attack when in combat.": "- 战斗时触发爆发攻击。",
    "A number of the game's functions are quickly and easily accessible via keyboard buttons. These are as follows:": "游戏的许多功能都可以通过键盘按钮快速轻松地访问，如下所示：",
    "Amazing": "惊人",
    "Armour pieces lose their positive protection stats - negative stats will still have an effect.": "盔甲部件失去了积极的保护统计数据 - 消极的统计数据仍然会产生影响。",
    "Armour Shred": "护甲碎片",
    "Badges are one-time awards for performing certain actions or meeting certain criteria as you play the game, and the Badges tab shows which ones are available and which ones are earned.": "徽章是您在玩游戏时执行某些操作或满足某些标准时获得的一次性奖励，“徽章”选项卡显示哪些徽章可用以及哪些徽章是已获得的。",
    "Bleed": "流血",
    "Confuse": "迷惑",
    "Debuffs": "减益效果",
    "Defence": "防御",
    "Disarm": "解除武装",
    "Doom": "厄运",
    "Drain": "汲取",
    "Durability and Decay": "耐久性和腐烂",
    "During combat, these buttons are replaced with in-combat functions - the ability to flee, activate a burst attack, or use your equipped potion.": "在战斗中，这些按钮会被战斗中的功能所取代 - 逃跑、激活爆发攻击或使用装备的药水的能力。",
    "Each badge earned increases experience and seeds gained from combat by 2%, after all other effects and modifiers.": "扣除所有其他效果和修饰符后，获得的每个徽章都会使战斗中获得的经验和种子增加 2%。",
    "Each stat, in addition to having a direct effect, has a secondary effect that scales with its' value, subject to diminishing returns.": "每个统计数据除了具有直接影响外，还具有与其值成比例的次要影响，但收益递减。",
    "Each zone has a level range, which dictates the power of monsters that can be found there, as well as the items you can purchase from the store.": "每个区域都有一个等级范围，这决定了在那里可以找到的怪物的力量，以及您可以从商店购买的物品。",
    "Equipped items can be repaired. While the repair function is running, you may change your equipment at will - the function stops once all currently equipped items are repaired.": "装备的物品可以进行修复，修复功能运行期间，你可以随意更换装备，一旦当前装备的物品全部修复完毕，该功能就会停止。",
    "Equipped items will become damaged as they are used - the amount of durability they can have scales with their level.": "装备好的物品会在使用时受到损坏——它们的耐久度会随着等级的变化而变化。",
    "Good": "好的",
    "Great": "伟大的",
    "Higher quality weapons can possess one of ten unique debuffs, which activate to assist in combat. These are as follows:": "更高质量的武器可以拥有十种独特的减益效果之一，这些减益效果可以激活以协助战斗。这些减益效果如下：",
    "If you win, you are given the enemy's equipped items, some experience and some seeds. If you lose, you'll be penalised a percentage of the experience you have on hand.": "如果你赢了，你会得到敌人的装备、一些经验和一些种子；如果你输了，你会受到你手头经验的一定比例的惩罚。",
    "Information about the last major game update appears in the Updates tab.": "有关上次主要游戏更新的信息显示在“更新”选项卡中。",
    "It takes care of most of the game's core loop - the fighting, repairing and selling of items, leaving the player to make other decisions.": "它负责游戏的大部分核心循环——战斗、修理和销售物品，让玩家做出其他决定。",
    "It won't change your equipment, make purchases on your behalf, spend stat or skill points, or attempt to fight area bosses.": "它不会改变你的装备、代表你进行购买、花费统计数据或技能点，或尝试与区域首领战斗。",
    "Item Quality": "物品质量",
    "Items can be discarded, for when you just don't care about them.": "当您不关心物品时，可以丢弃它们。",
    "Items can be equipped at any time (even during battles), which is useful to know if you need a change of tack for a given encounter.": "可以随时装备物品（甚至在战斗中），这对于了解您是否需要针对特定​​遭遇改变策略很有用。",
    "Items can be locked, which prevents all actions against them other than equipping them - this includes the inventory cleaning function.": "物品可以被锁定，这可以防止除装备物品之外的所有针对物品的操作 - 这包括库存清理功能。",
    "Items can be scrapped, which provides the scrap you need for other upgrades and modifications.": "物品可以报废，这为您提供其他升级和修改所需的报废。",
    "Items can be sold for seeds, which are then used to buy new items in the store or upgrade existing ones.": "物品可以出售为种子，然后用于在商店购买新物品或升级现有物品。",
    "Items in the game can be generated with one of 5 quality levels (in order of least to most powerful):": "游戏中的物品可以以 5 个质量级别之一生成（按照从最弱到最强大的顺序）：",
    "Keybindings": "键绑定",
    "Multistrike": "多重打击",
    "Normal": "普通的",
    "Offence": "罪行",
    "Paralysis": "麻痹",
    "Poor": "贫穷的",
    "Repairing items is free, only taking time. The speed of repairing items scales with your level. You may end the repairing state early by entering combat.": "修复物品是免费的，只需要时间。修复物品的速度与你的等级成正比。你可以通过进入战斗提前结束修复状态。",
    "Resetting stats costs some scrap, with the cost scaling with the number of stat points spent.": "重置统计数据会产生一些废品，成本随着消耗的属性点数的增加而增加。",
    "Since the level of items generated in the store is capped based on your current level and the zone level, moving to the highest zone you can reach ensures that store items are the best they can be.": "由于商店中生成的物品等级根据您当前的等级和区域等级而受到限制，因此移动到您可以到达的最高区域可确保商店物品达到最佳状态。",
    "Skills that are not yet available to upgrade will be faded out - these will open up as you raise existing skills to their maximum level.": "尚未可升级的技能将逐渐消失 - 当您将现有技能提升到最高水平时，这些技能将会开放。",
    "Sleep": "沉睡",
    "Slow": "减速",
    "Spend scrap to apply a new debuff to an existing weapon of Good quality or better.": "花费废料对优质或更好品质的现有武器应用新的减益效果。",
    "Spend scrap to upgrade your equipment's quality, which makes its' stats scale better with levels and sometimes adds new effects.": "花费废料来升级你的装备的质量，这使得它的统计数据随着等级的增加而更好，有时还会增加新的效果。",
    "Spend seeds to acquire new equipment and potions.": "花费种子来购买新设备和药水。",
    "Spend seeds to upgrade your equipment's level, improving its' stats.": "花费种子来升级你的装备等级，提高其属性。",
    "The 'Clean Inventory' button will process all unlocked items you are currently carrying, performing a specific action on each one based on choices made on the Options tab.": "“清理库存”按钮将处理您当前携带的所有未锁定物品，并根据“选项”选项卡上所做的选择对每件物品执行特定操作。",
    "The 'Save Game' and 'Reset Game' buttons are, hopefully, self-explanatory - but they have a note attached to them just in case!": "希望“保存游戏”和“重置游戏”按钮是不言自明的 - 但它们附有注释以防万一！",
    "The Auto-battle system is what makes the game semi-idle.": "自动战斗系统使游戏变得半空闲。",
    "The auto-battle system uses this function as part of its' operation, and will in fact halt if the inventory remains full once this function has been triggered.": "自动战斗系统使用此功能作为其操作的一部分，并且一旦触发此功能，如果库存仍然满，实际上会停止。",
    "The burst attack is an instant strike delivered with your equipped weapon, with a base cooldown of 10 seconds.": "爆发攻击是用你所装备的武器进行的即时攻击，基本冷却时间为 10 秒。",
    "The combat tab plays host to the combat log, and functions related to combat.": "战斗选项卡负责战斗日志以及与战斗相关的功能。",
    "The Constitution stat has a chance to gain two points on level up instead of one.": "体质属性有机会在升级时获得两点而不是一点。",
    "The controls here determine what happens to each item type and quality when that button is pressed.": "这里的控件决定按下该按钮时每个项目类型和质量会发生什么。",
    "The game features a total of fourteen different zones, accessible via the Zones tab once you defeat your first area boss.": "该游戏共有十四个不同的区域，一旦您击败第一个区域老板，就可以通过“区域”选项卡访问。",
    "The game's three skill trees become available once you have earned your first skill point at level 5, and points are earned every other level afterwards.": "一旦您在第 5 级获得第一个技能点，游戏的三个技能树就会变得可用，之后每隔一个级别都会获得积分。",
    "The inventory cleaning function makes item management easier, by running a bulk operation when you click the button on the Items tab.": "库存清理功能通过单击“项目”选项卡上的按钮运行批量操作，使项目管理变得更加容易。",
    "The Items tab lists all of your currently held items, and provides various options for what you can do with them:": "“项目”选项卡列出了您当前持有的所有项目，并提供了各种选项来说明您可以使用它们执行哪些操作：",
    "The options tab provides controls for some of the game's systems:": "选项选项卡提供了一些游戏系统的控件：",
    "The Player tab holds your stats and the panel which allows you to assign stat points.": "“玩家”选项卡包含您的统计数据和允许您分配属性点的面板。",
    "The shop will periodically restock, and a manual restock can be forced by moving between zones if you have more than one available.": "商店会定期补货，如果您有多个可用区域，则可以通过在区域之间移动来强制手动补货。",
    "The Skills tab lets you interact with the skill trees once it becomes available. Skill points can be moved at will between skills at any time, even in combat.": "一旦技能树可用，“技能”选项卡可让您与技能树进行交互。技能点可以随时在技能之间随意移动，甚至在战斗中也是如此。",
    "The Store tab is your one-stop shop for acquiring new equipment, as well as upgrading existing pieces that you wish to keep. It has the following functions:": "商店选项卡是您获取新装备以及升级您想要保留的现有装备的一站式商店。它具有以下功能：",
    "This function will not touch Potions, regardless of locked status.": "无论锁定状态如何，此功能都不会触及药水。",
    "tree focuses on effects that don't fit into either of the other trees, such as boosted resource gains or experience.": "树专注于不适合其他树的效果，例如增加资源增益或经验。",
    "tree focuses on effects that increase damage dealt to enemies, and effects that occur when attacking.": "树专注于增加对敌人造成的伤害的效果，以及攻击时发生的效果。",
    "tree focuses on effects that reduce damage taken from enemies, and effects that occur when attacked.": "树专注于减少敌人造成的伤害的效果，以及受到攻击时发生的效果。",
    "Upon entering combat, both combatants will trade blows until one of them emerges victorious.": "进入战斗后，双方将互相攻击，直到其中一方取得胜利。",
    "Weapons have their damage values halved, and no longer apply their debuffs.": "武器的伤害值减半，并且不再施加减益效果。",
    "When an item reaches zero durability, it breaks, losing some of its' functionality:": "当一个物品的耐用性达到零时，它就会损坏，失去一些功能：",
    "When leveling up, you gain one point in each stat, plus another point in the stat that relates to your equipped weapon, as well as an additional stat point to spend freely.": "升级时，您在每个统计数据中获得一分，再加上与您所装备的武器相关的统计数据中的另一点，以及可自由花费的额外属性点。",
    "While a sixth quality level does exist, it is not attainable by players, and is used entirely for equipment held by area bosses.": "虽然第六品质等级确实存在，但玩家无法达到，并且完全用于区域首领持有的装备。",
    "While not in combat, there are buttons here to repair equipment, look for a fight, or engage the area boss once you've reached the level cap for the zone.": "当不在战斗中时，这里有一些按钮可以修复装备、寻找战斗，或者在达到该区域的等级上限后与区域首领交战。",
    "+Max": "+最大",
    "Gives a 4.68% to restore 6 HP when attacking.": "攻击时有 4.68% 恢复 6 点生命值。",
    "Increases damage dealt with magic weapons.": "增加魔法武器造成的伤害。",
    "Increases damage dealt with melee weapons.": "增加近战武器造成的伤害。",
    "Increases damage dealt with ranged weapons.": "增加远程武器造成的伤害。",
    "Increases maximum health and health restored when idle.": "增加最大生命值和闲置时恢复的生命值。",
    "Reset Your Stats": "重置您的属性点",
    "Stat Point Allocation": "属性点分配",
    "Clean Inventory": "清理库存",
    "Combat Log": "战斗日志",
    "Discard": "丢弃",
    "Equip": "装备",
    "Equipped Items": "装备物品",
    "Go Hunting": "去打猎",
    "Healing Tincture": "治疗酊剂",
    "Magic": "魔法",
    "Repair": "修理",
    "Restores 30% of your maximum health. Simple, but effective.": "恢复 30% 的最大生命值。简单但有效。",
    "Scrap": "报废",
    "Sell": "出售",
    "Unremarkable Scepter": "不起眼的权杖",
    "Unremarkable War Staff": "不起眼的战争法杖",
    "Usable Tower Shield": "可用的塔盾",
    "A Good Offense": "一次良好的进攻",
    "A Habit is Born": "习惯诞生",
    "Activate the autobattle function.": "启动自动战斗功能。",
    "Overcoat": "大衣",
    "Spell Focus": "法术专注",
    "Alchemical Bombardment": "炼金轰击",
    "All Change, Please": "所有更改，请",
    "ALL HAIL THE ALMIGHTY STORE GOD!": "所有人都向全能的商店神致敬！",
    "All the magical power in the world still couldn't stop you from killing him.": "世上所有的魔法力量都无法阻止你杀死他。",
    "Amazing Armour": "惊人的盔甲",
    "Amazing Weapons": "惊人的武器",
    "Any Scotsman will tell you nakedness is an incredible deterrent.": "任何苏格兰人都会告诉你裸体是一种令人难以置信的威慑力。",
    "Apply random debuffs to your weapons 100 times.": "对你的武器施加随机减益效果 100 次。",
    "Armour Hoarder": "盔甲囤积者",
    "Assisted Suicide": "协助自杀",
    "Autobattle Settings": "自动战斗设置",
    "Aversion to Clicking": "厌恶点击",
    "Baby Steps": "婴儿学步",
    "Back to Reality": "回到现实",
    "Banditry isn't a good career path, 0/10, would not recommend.": "土匪不是一个好的职业道路，0/10，不推荐。",
    "Beyond Divinity": "超越神性",
    "Blue in the Face": "脸上发青",
    "Bookish Type": "书卷气型",
    "Broken In": "闯入",
    "Broken Mouse Convention": "破坏鼠标公约",
    "Burning things are notoriously hard to loot.": "众所周知，燃烧的东西很难抢劫。",
    "Calm Down Dear": "冷静点亲爱的",
    "Can't touch this, na na na na, na na, na na.": "不能碰这个，娜娜娜娜，娜娜，娜娜。",
    "CAPITALISM!": "资本主义！",
    "Cause an enemy to apply their own weapon's debuff to themselves.": "使敌人将自己武器的减益效果应用到自己身上。",
    "Cause an enemy to deal the killing blow to itself.": "使敌人对自己造成致命一击。",
    "Clean Inventory Settings": "清理库存设置",
    "Clear Save": "清除保存",
    "Coming to a Point": "到达一个点",
    "Concoctions for all occasions!": "适合所有场合的混合物！",
    "Coup de Grace": "致命一击",
    "Cripple (Slow) - 10 sec.": "瘫痪（减速）- 10 秒。",
    "Curl up in an armchair with your favourite read - you deserve it.": "蜷缩在扶手椅上阅读您最喜爱的书籍 - 这是您应得的。",
    "Deal 1,000,000 damage with all three weapon types.": "使用所有三种武器类型造成 1,000,000 点伤害。",
    "Deal the killing blow to an enemy while your armour is broken.": "当你的盔甲被破坏时，对敌人造成致命一击。",
    "Deal the killing blow to an enemy while your weapon and armour are broken.": "当你的武器和盔甲被破坏时，对敌人造成致命一击。",
    "Deal the killing blow to an enemy while your weapon is broken.": "当你的武器损坏时，对敌人造成致命一击。",
    "Death from above!": "死亡从天而降！",
    "Defeat 1,000 consecutive enemies without dying or fleeing.": "连续击败 1,000 名敌人，且不死亡或逃跑。",
    "Defeat 1,000 enemies.": "击败 1,000 名敌人。",
    "Defeat a boss without taking any damage.": "在不受任何伤害的情况下击败 Boss。",
    "Defeat an enemy without taking any damage.": "在不受任何伤害的情况下击败敌人。",
    "Defeat Ashen Berserker in the Ash Cultist Outpost.": "击败灰烬教徒前哨站的灰烬狂战士。",
    "Defeat the Archbishop of the Hollow in the Weary Hollow Chapel.": "击败疲倦空心教堂的空心大主教。",
    "Defeat the Bandit Mastermind at The Fallen Pillar.": "击败堕落之柱的强盗主谋。",
    "Defeat the Chief Engineer of The Swiftsteel Workshop.": "击败 斯威夫特钢铁公司 车间的总工程师。",
    "Defeat the Chromatic Broodmother, atop the Dragons' Crown.": "击败龙冠顶上的彩色巢母。",
    "Defeat the Ethereal Train Driver at The Final Stop.": "在终点站击败空灵的火车司机。",
    "Defeat the Grand Archsage in the Ley Line Research Facility.": "击败魔网研究设施中的大圣贤。",
    "Defeat the High Ashlord atop the Pillar of Ash.": "击败灰烬之柱顶上的至高灰烬领主。",
    "Defeat the Lumbering Spore Giant within the Echoing Passage.": "击败回音通道内的笨重孢子巨人。",
    "Defeat the Magma Wyrm deep within The Smouldering Heart.": "击败闷燃之心深处的岩浆巨龙。",
    "Defeat the Massive Cave Troll in the Whispering Cave.": "击败低语洞穴中的巨型洞穴巨魔。",
    "Defeat the Reaper beyond the Veil.": "击败面纱之外的收割者。",
    "Defeat the Shadow of the Ashlord at Reality's Edge.": "在现实边缘击败阿什领主之影。",
    "Defeat the Swamp Behemoth in the Dawn's Light Swamp.": "击败黎明之光沼泽中的沼泽巨兽。",
    "Defence of the Ancients": "古人的防御",
    "Definitely not getting carried.": "绝对不会被带走。",
    "Deliver 1,000 Burst Attacks.": "进行 1,000 次爆发攻击。",
    "Deliver the finishing blow to a foe with a Burst Attack.": "通过爆发攻击对敌人进行最后一击。",
    "Die from a Damage over Time effect while your enemy is suffering from Sleep.": "当你的敌人处于睡眠状态时，你会因持续伤害效果而死亡。",
    "Die from an attack delivered to yourself.": "死于对自己的攻击。",
    "DISCARD": "丢弃",
    "Disposable Income": "可支配收入",
    "Divine Intervention": "神圣干预",
    "Do it for me, I'm too... tired. Yes... tired.": "帮我做吧，我太……累了。是的……累了。",
    "Don't Fear the Reaper": "不要害怕收割者",
    "Don't trust the automatic save feature? This button is for you! Works 100% of the time! Honest!": "不相信自动保存功能？这个按钮适合您！100% 有效！诚实！",
    "End a fight with more health than you started it with.": "结束一场战斗时，你的生命值会比开始时更高。",
    "Enter 1,000 battles without using the autobattle function.": "在不使用自动战斗功能的情况下进入 1,000 场战斗。",
    "Enter combat for the first time.": "第一次进入战斗。",
    "Equip a weapon and piece of armour of Great quality or better.": "装备优质或更高品质的武器和盔甲。",
    "Ever heard of 'distraction value'?": "听说过“分散注意力价值”吗？",
    "Expensive Tastes": "口味昂贵",
    "Fancy a fresh start? We can do that. Push the button and we'll forget you were ever even here. (This is a complete and permanent removal of all save data!)": "想要一个新的开始吗？我们可以做到。按下按钮，我们就会忘记您曾在这里。（这是对所有保存数据的彻底且永久的删除！）",
    "Feeling Broody": "感觉布罗迪",
    "Fill your inventory to the maximum capacity.": "将您的库存填满至最大容量。",
    "Fill your inventory with only Amazing quality items.": "仅用优质物品填充您的库存。",
    "Flawless Victory": "完美的胜利",
    "Flows surprisingly well in large quantities.": "大量流动时出奇地好。",
    "Full House": "客满",
    "Gain 1,000 scrap from converting items.": "通过转换物品获得 1,000 碎片。",
    "Gain 1,000,000 seeds from selling items.": "通过出售物品获得 1,000,000 粒种子。",
    "Gas Grenades": "毒气手榴弹",
    "Give your character a name.": "给你的角色起一个名字。",
    "Glad there's no immovable objects here.": "很高兴这里没有不可移动的物体。",
    "God Complex": "神情结",
    "Golden Breastplate": "金色胸甲",
    "Good Armour": "不错的盔甲",
    "Good Weapons": "不错的武器",
    "Gravity can go ahead and bite me.": "重力会继续咬我。",
    "Great Armour": "伟大的盔甲",
    "Great Weapons": "伟大的武器",
    "Happy Customer": "快乐的顾客",
    "Have 100 stat points allocated to Constitution.": "将 100 点属性点分配给宪法。",
    "Have 100 stat points allocated to Dexterity.": "将 100 点属性点分配给敏捷。",
    "Have 100 stat points allocated to Intelligence.": "有 100 个属性点分配给智力。",
    "Have 100 stat points allocated to Strength.": "将 100 点属性点分配给力量。",
    "Have a full inventory of Great or better quality armours.": "拥有优质或更高品质盔甲的完整库存。",
    "Have a full inventory of Great or better quality weapons.": "拥有完整的优质或更高质量的武器。",
    "Have a total of 200 stat points allocated.": "总共分配了 200 个属性点。",
    "Have a total of 50 skill points allocated.": "总共分配了50个技能点。",
    "Have at least three Amazing quality items in your inventory": "您的库存中至少有三件令人惊叹的优质物品",
    "Have at least three Great quality items in your inventory.": "您的库存中至少有三件优质物品。",
    "Have the game autosave 100 times.": "让游戏自动保存 100 次。",
    "He shoots... and hits the barn door this time!": "他开枪了……这次击中了谷仓门！",
    "Metal": "金属",
    "Here's to the next 10k!": "下一个 10k 即将到来！",
    "High and Mighty": "高高在上",
    "Hoisted By My Own Petard": "被我自己的石头举起",
    "Hold your breath.": "屏住呼吸。",
    "How can you be me, when I'm me?": "当我是我时，你怎么能是我？",
    "How does it even stay in there?": "它怎么会留在那儿呢？",
    "How many times do we have to teach you this lesson, old man?": "老伙计，这个教训我们要教你多少次？",
    "I am invincible!": "我无敌了！",
    "I could do this ALL DAY!.": "我可以做一整天！",
    "I don't recommend trying to verify the taste of purple.": "我不建议尝试验证紫色的味道。",
    "I have no use for these pathetic toys!": "这些可怜的玩具我没有用！",
    "I promise this won't hurt. Much.": "我保证这不会造成太大伤害。",
    "I used to be indecisive, but now I'm not so sure.": "以前我很犹豫，但现在我不太确定了。",
    "I'm bigger than you and I'm higher in the food chain!": "我比你大，而且我在食物链中的地位更高！",
    "If you had several thousand kids, you would too.": "如果你有几千个孩子，你也会的。",
    "If you're interested, I also have this rock that wards off tigers.": "如果你有兴趣的话，我这里还有一块驱虎石。",
    "IGNORE": "忽略",
    "Indecisive": "优柔寡断",
    "Inflict your own weapon's debuff on yourself.": "对自己造成自己武器的减益效果。",
    "Initiate a repair of your equipment": "开始维修您的设备",
    "Interrupt the repair function by entering combat while it is in progress.": "在修复功能正在进行时进入战斗来中断修复功能。",
    "It never hurts to be sure.": "确定一下总是没有坏处的。",
    "It's just a stab in the face, that's all. You won't feel a thing.": "只是脸上被刺了一下而已，你不会有任何感觉。",
    "Jack of All Trades": "万事通",
    "Just don't start drinking your own urine.": "只是不要开始喝自己的尿液。",
    "Keyboard Cat": "键盘猫",
    "Knocking him off his several hundred foot high horse.": "将他从数百英尺高的马上撞下来。",
    "Lacking in Flavour": "缺乏风味",
    "Lightning in a Bottle": "瓶中闪电",
    "Like a Boss": "像一个老板一样",
    "Living on a Prayer": "靠祷告生活",
    "Longcoat": "长大衣",
    "Make your first purchase from the store.": "从商店进行第一次购买。",
    "Manual Labour": "体力劳动",
    "Mass of Molasses": "大量糖蜜",
    "Master of none.": "无为大师。",
    "May we all be blessed with everlasting prosperity.": "愿我们大家都能得到永远的繁荣。",
    "Maybe if he'd read that book, he would have learned how to not die.": "也许如果他读了那本书，他就会学会如何不死。",
    "Maybe it's best you leave everything at defaults after all...": "毕竟，也许最好将所有内容保留为默认值......",
    "Maybe this one will be worth it?": "也许这个值得吗？",
    "MC Hammer Special": "MC 锤子特价",
    "Mind Control (Confuse) - 5 sec.": "精神控制（混乱）- 5 秒。",
    "Mmm... bland...": "嗯……平淡……",
    "Name yourself after the game's developer, Psychemaster": "以游戏开发者 Psychemaster 的名字命名",
    "Nerve Strike (Paralysis) - 10 sec.": "神经打击（麻痹）- 10 秒。",
    "Normal Armour": "普通装甲",
    "Normal Weapons": "普通武器",
    "Now if only you could wear them all at once...": "现在如果你能同时穿上它们就好了……",
    "Now you know how it feels!": "现在你知道那是什么感觉了！",
    "Now you'll never leave. Muahahahahahahahaha!!!": "现在你再也不会离开了。哈哈哈哈哈哈哈哈哈！！！",
    "OK, so 100 isn't unlimited, so what! It sounded cool, okay?": "好吧，所以 100 并不是无限的，那又怎样！听起来很酷，好吗？",
    "Once you start, you just can't stop! Until it's fixed.": "一旦开始，就无法停止！直到问题解决为止。",
    "Only really good for dying in style.": "只适合优雅地死去。",
    "Original badge, do not steal.": "原装徽章，请勿盗用。",
    "Outgrown": "已经过时了",
    "Own one of every type of potion.": "每种药水都拥有一种。",
    "Percentage of health remaining to automatically flee?": "剩余生命值自动释放的百分比？",
    "Percentage of item durability remaining to start repairing?": "需要开始修复的物品剩余耐久度百分比？",
    "Pinpoint Accuracy": "精确定位",
    "Play it again, Sam!": "再玩一次，萨姆！",
    "Poor Armour": "装甲较差",
    "Poor Weapons": "糟糕的武器",
    "Potion Hoarder": "药水囤积者",
    "Powerful Crossbow": "强力弩",
    "Praise be to RNGesus!": "赞美太阳！",
    "Problem Solved": "问题解决了",
    "Promote an item to Great quality without providing a name.": "在不提供名称的情况下将商品提升为优质。",
    "Promote an item to Great quality without providing flavour text.": "在不提供风味文字的情况下将商品提升为优质。",
    "Promote synergy!": "促进协同效应！",
    "Punching Mirrors": "冲孔镜",
    "Purchase Items": "购买物品",
    "Rags to Riches": "白手起家",
    "Ranged": "远程",
    "Reach level 50 without buying anything in the store.": "无需在商店购买任何东西即可达到 50 级。",
    "Reach level 50 without providing custom names or descriptions for anything.": "无需提供任何内容的自定义名称或描述即可达到 50 级。",
    "Reset your stats a total of 100 times.": "总共重置您的统计数据 100 次。",
    "Reset your stats.": "重置您的统计数据。",
    "Rolling the Bones": "滚骨头",
    "Save Game": "保存游戏",
    "Save Options": "保存选项",
    "SCRAP": "废料",
    "See that? That's you, right there.": "看到了吗？那就是你，就在那里。",
    "SELL": "出售",
    "Skullcrusher Mountain": "碎颅山",
    "Sleeping Gas (Sleep) - 15 sec.": "睡眠气体（睡眠）- 15 秒。",
    "So this is how it feels...": "所以这就是感觉...",
    "Sometimes you just need a personal touch.": "有时您只需要个人风格。",
    "Spend 500 scrap in the store.": "在商店花费 500 碎片。",
    "Spend at least 1,000,000 seeds in the store.": "在商店中花费至少 1,000,000 个种子。",
    "Spend at least 10,000 seeds in the store.": "在商店中花费至少 10,000 颗种子。",
    "Spend at least 100,000 seeds in the store.": "在商店里花费至少100,000个种子。",
    "Stop hitting yourself!": "别再打自己了！",
    "Sucker": "吸盘",
    "Surpassing the Master": "超越大师",
    "Take at least 25 attacks in one battle.": "在一场战斗中至少接受 25 次攻击。",
    "Take my hand and we'll make it, I swear!": "握住我的手，我们一定能成功，我发誓！",
    "Taking a more direct approach to mindless violence.": "对无意识的暴力采取更直接的方法。",
    "Tarred With Their Own Brush": "用自己的刷子涂柏油",
    "Tastes like Purple": "味道像紫色",
    "That'll do just fine, back to work!": "这样就好了，回去工作吧！",
    "That's from talking about it, by the way.": "顺便说一句，这是从谈论它开始的。",
    "That's the best defence, you know!": "这就是最好的防守，你知道的！",
    "The Only Way is Up": "只有向上一条路",
    "The Personal Touch": "个人风格",
    "The Survivalist": "生存主义者",
    "The Trade Blockade": "贸易封锁",
    "The Trade Parade": "贸易游行",
    "The Unstoppable Force": "不可阻挡的力量",
    "There's a first time for everything.": "凡事都有第一次。",
    "This bag is really, REALLY heavy.": "这个包真的非常非常重。",
    "This service will terminate here. Please check all personal belongings when leaving the train.": "本次服务至此结束，下车时请检查所有个人物品。",
    "This, do I drink to thee...": "这个，我给你干杯吗……",
    "Throw away 1,000 items.": "扔掉 1,000 件物品。",
    "Time For A Shower": "淋浴时间",
    "Toggle activation state of auto-battle:": "切换自动战斗激活状态：",
    "Tonight I'm going to suck... your blood!": "今晚我要吸……你的血！",
    "Too Hot to Handle": "太热而无法处理",
    "Trolling the Troll": "拖拽巨魔",
    "Trust Issues": "信任问题",
    "Turn On": "打开",
    "Unimaginative": "缺乏想象力",
    "Unlimited Power!": "无限力量！",
    "Composite Bow": "复合弓",
    "Use Divine Shield to survive a blow that would otherwise have killed you.": "使用圣盾来抵御本来会杀死你的打击。",
    "Use keybindings to perform game actions 1,000 times.": "使用按键绑定执行游戏操作 1,000 次。",
    "Use potions to inflict debuffs on enemies 100 times.": "使用药剂对敌人造成 100 次减益效果。",
    "Use the manual save feature.": "使用手动保存功能。",
    "Vampirism": "吸血鬼主义",
    "Violent headbanging not required.": "不需要暴力头部撞击。",
    "War of Attrition": "消耗战",
    "We've Got You Covered": "我们为您服务",
    "Weapon Hoarder": "武器囤积者",
    "Well, that was underwhelming.": "嗯，那真是令人印象深刻。",
    "What Does This Button Do?": "这个按钮有什么作用？",
    "What use is being a millionaire when society as we know it has collapsed?": "当我们所知道的社会已经崩溃时，成为百万富翁还有什么用呢？",
    "Where is your god now?": "你的上帝现在在哪？",
    "Where We're Going, We Don't Need Armour": "我们要去的地方，我们不需要盔甲",
    "Where We're Going, We Don't Need Gear": "我们要去的地方，我们不需要装备",
    "Where We're Going, We Don't Need Weapons": "我们要去的地方，我们不需要武器",
    "Wherefore Art Thou, Romeo?": "为何你偏偏是罗密欧？",
    "Win a fight having entered it with less than 25% health.": "在生命值低于 25% 的情况下赢得一场战斗。",
    "Win a fight with less than 5% of your total health remaining.": "在你的总生命值剩余不到 5% 的情况下赢得一场战斗。",
    "With all the seeds you've provided, we hired some dancers to work out front. You're welcome.": "有了你提供的所有种子，我们雇了一些舞者在前面锻炼。不客气。",
    "With this level of filth, you'll see me again in about a week.": "有了这种程度的肮脏，大约一周后你就会再次见到我。",
    "You know there were guys who used to fight EXCLUSIVELY with their fists?": "你知道有些人过去只用拳头打架吗？",
    "You know what this world could use? A skull fortress!": "你知道这个世界可以用什么吗？骷髅堡垒！",
    "You never run out of ways to murder things, do you?": "你永远不会用尽谋杀的方法，不是吗？",
    "You'll come crawling back soon enough!": "你很快就会爬回来的！",
    "You've beaten Death itself, there is nothing left for you here.": "你已经打败了死亡本身，这里已经没有什么可以留给你了。",
    "Your collection is worth HOW MUCH?!?!?": "您的收藏值多少钱？！？！？",
    "Your data is safe in our hands.": "您的数据在我们手中是安全的。",
    "Your keyboard still works, right? There's always MouseKeys!": "您的键盘仍然可以使用，对吧？总有鼠标键！",
    "A Habit is Born": "习惯是天生的",
    "Repairing items...": "正在修理物品...",
    "Repairs complete.": "修理完毕。",
    "Crossbow": "弩",
    "Badge earned: A Habit is Born": "获得徽章：习惯的诞生",
    "Burst Attack": "爆发攻击",
    "damage.": "伤害。",
    "experience.": "经验值。",
    "Flee From Combat": "逃离战斗",
    "for": "",
    "Gained": "获得了",
    "Repairing items...": "正在修理物品...",
    "Repairs complete.": "修理完成。",
    "seeds.": "种子。",
    "Simple Tower Shield": "简单的塔盾",
    "Stealthy Tiger": "隐秘的老虎",
    "Use": "使用",
    "You got": "你得到了",
    "You won!": "你赢了！",
    "experience...": "经验...",
    "Game saved.": "游戏已保存。",
    "Hibernating Boar": "冬眠的野猪",
    "Mind Control": "精神控制",
    "Mind Control (5 sec)": "精神控制（5秒）",
    "Upgraded Shuriken": "升级手里剑",
    "You lose": "你失去了",
    "You lost...": "你输了...",
    "You suffer from Mind Control.": "你遭受了精神控制。",
    "Melee": "近战",
    "Wrap": "披肩",
    "Lurking Lion": "潜伏的狮子",
    "Polished Buckler": "抛光圆盾",
    "Usable Shiv": "可用的匕首",
    "Bloodthirst (Drain) - 10 sec.": "嗜血（汲取）- 10 秒。",
    "Brown Bear": "棕熊",
    "Reinforced Chestplate": "强化胸甲",
    "Well-Maintained Scepter": "保养良好的权杖",
    "Destroyed": "已销毁",
    "Equipped": "装备齐全",
    "Sold": "已出售",
    "Usable Shortsword": "可用的短剑",
    "health.": "生命值。",
    "damage! (Critical)": "伤害! (暴击)",
    "Kite Shield": "风筝盾",
    "Your Constitution restored": "你的体质恢复了",
    "Wrap": "披肩",
    "blocked)": "已格挡)",
    "Giant Spider": "巨型蜘蛛",
    "Worthless Quarterstaff": "毫无价值的军需手杖",
    "Darts": "飞镖",
    "Frayed Buckler": "磨损圆盾",
    "You dodged the incoming attack.": "你躲开了即将到来的攻击。",
    "Burst Attack Recharging": "爆发攻击充能",
    "activated.": "已激活。",
    "Arbalest": "强弩",
    "Simple Kite Shield": "简单的风筝盾",
    "Arbalest": "强弩",
    "Battlestaff": "战杖",
    "Brass Knuckles": "指节铜环",
    "Brigandine": "镶甲",
    "Buckler": "圆盾",
    "Crozier": "牧杖",
    "Deflector": "导向板",
    "Hand-Cannon": "手持加农炮",
    "Jerkin": "紧身皮袄",
    "Kite Shield": "风筝盾",
    "Poncho": "斗篷",
    "Quarterstaff": "军需杖",
    "Quickblade": "快刀",
    "Shortbow": "短弓",
    "Shorts": "短裤",
    "Shuriken": "手里剑",
    "Slingshot": "弹弓",
    "Spellblade": "法术之刃",
    "Throwing Knife": "飞刀",
    "Tome of Thunder": "雷霆之书",
    "Tonfa": "通法",
    "Tunic": "外衣",
    "Wrap": "披肩",
    "\"Hey, does this rag smell like chloroform to you?\"": "“嘿，你觉得这块抹布闻起来像氯仿吗？”",
    "\"How to Maim Your Dragon\"": "《如何残害你的龙》",
    "A lightning rod, basically.": "基本上是避雷针。",
    "Absolute Zero": "绝对零度",
    "Adder's Fang": "阿德尔的尖牙",
    "Anaesthesia (Sleep) - 15 sec.": "麻醉（睡眠）- 15 秒",
    "Arm Shot (Disarm) - 15 sec.": "武装射击（解除武装）- 15 秒。",
    "Barrage (Multistrike) - 15 sec.": "弹幕（多重打击）- 15 秒。",
    "Be very, very quiet...": "非常非常安静...",
    "Bear the weight of your crimes!": "承受你所犯下的罪行！",
    "Bitter Cold (Paralysis) - 15 sec.": "严寒（麻痹）- 15 秒。",
    "Bloodthirst (Drain) - 15 sec.": "嗜血（汲取）- 15 秒。",
    "Bolt-Action Rifle": "栓动步枪",
    "Break Weapon (Disarm) - 15 sec.": "破坏武器（缴械）- 15 秒。",
    "Brigandine": "镶甲",
    "Bringing a sword to a gun fight.": "带着剑去枪战。",
    "But how am I meant to attack?": "但我该如何攻击呢？",
    "Butterfinger Brew": "黄油手指啤酒",
    "Causes an excessive amount of sweat to interfere with grip.": "导致过多的汗水干扰抓地力。",
    "Cauterize (Drain) - 15 sec.": "烧灼（汲取）- 15 秒。",
    "Chainmail Bikini": "链甲比基尼",
    "Chestplate": "胸板",
    "Chloroform Concoction": "氯仿混合物",
    "Comatose (Sleep) - 10 sec.": "昏迷（睡眠）- 10 秒",
    "Comet Chaser": "彗星追逐者",
    "Concentrated Absinthe": "浓缩苦艾酒",
    "Concussion (Slow) - 15 sec.": "脑震荡（慢）- 15 秒",
    "Constitution increased by": "宪法增加了",
    "Contagion": "传染",
    "Counting Sheep (Sleep) - 15 sec.": "数羊（睡眠）- 15 秒",
    "Covers all the important bits.": "涵盖了所有重要的部分。",
    "Cripple (Slow) - 15 sec.": "瘫痪（慢）- 15 秒。",
    "Cuirass": "胸甲",
    "Dark Omen (Doom) - 5 sec.": "黑暗预兆（末日）- 5 秒。",
    "Dazzle (Disarm) - 15 sec.": "眩晕（解除武装）- 15 秒。",
    "Death Sentence": "死刑",
    "Decrepit Arbalest": "破旧的强弩",
    "Decrepit Scepter": "破旧的权杖",
    "Decrepit Tome of Flame": "破旧的火焰宝典",
    "Dexterity increased by": "敏捷度增加",
    "Diplomacy (Armour Shred) - 15 sec.": "外交（破甲）- 15 秒。",
    "Diplomatic immunity!": "外交豁免权！",
    "Disarmed (Disarm) - 10 sec.": "解除武装（解除武装）- 10 秒。",
    "Do not try chasing comets at home.": "不要尝试在家里追逐彗星。",
    "Don't stare directly at it.": "不要直视它。",
    "Dragon Chainmail": "龙链甲",
    "Dragon's Breath": "龙息",
    "Dual-Wielded Shields": "双持盾牌",
    "Edge of Depravity": "堕落的边缘",
    "Encyclopedia of the Realm": "王国百科全书",
    "Especially effective against shark attacks.": "特别有效对抗鲨鱼袭击。",
    "Ether-Soaked Cloth": "乙醚浸布",
    "Excalibur": "神剑",
    "Find Weakness (Armour Shred) - 15 sec.": "寻找弱点（护甲碎片）- 15 秒。",
    "Flames of Tetradigm (Doom) - 5 sec.": "四元之焰（末日）- 5 秒。",
    "Flametongue": "火舌",
    "Frenzy (Multistrike) - 10 sec.": "狂乱（多重打击）- 10 秒。",
    "Generic Armour Name": "通用装甲名称",
    "Generic Bleed (Bleed) - 15 sec.": "通用出血（出血）- 15 秒。",
    "Generic Ranged Weapon": "通用远程武器",
    "Giant Armour Plate": "巨型装甲板",
    "Gift of the Cosmos": "宇宙的礼物",
    "Glows brighter than the sun.": "发出比太阳还要亮的光。",
    "Good for those long cold nights in camp.": "适合在营地度过漫长寒冷的夜晚。",
    "Gunblade": "枪刃",
    "has broken!": "坏了！",
    "Hat": "帽子",
    "Holy Light (Drain) - 15 sec.": "圣光（汲取）- 15 秒。",
    "Humans are so much more effective when encased in metal.": "当人类被金属包围时，效率会高得多。",
    "I think it's just misunderstood...": "我觉得这只是误会了...",
    "I wonder what we'll find today?": "我想知道今天我们会发现什么？",
    "If this won't stop attackers, the one wearing it will.": "如果这还不能阻止攻击者，那么佩戴它的人就能阻止。",
    "Illegal for use in Canada, caution advised.": "在加拿大使用是非法的，请谨慎使用。",
    "Incapacitated (Disarm) - 15 sec.": "丧失能力（解除武装）- 15 秒。",
    "Intelligence increased by": "智力增加",
    "It was padded all along!": "一直都是垫着的！",
    "It's bigger than you, and we all know bigger is better.": "它比你大，我们都知道越大越好。",
    "Judgement Bolt (Doom) - 5 sec.": "审判之箭（末日）- 5 秒。",
    "Judgement Staff": "审判杖",
    "Just keeps on giving.": "只是继续付出。",
    "Kevlar Vest": "凯夫拉背心",
    "Knowledge is power.": "知识就是力量。",
    "Kunai": "苦无",
    "Legplates": "腿甲",
    "Level up! You are now level 4": "升级！您现在已达到 4 级",
    "Mageblade": "法师之刃",
    "Making the stars align for you.": "让星星为你排列。",
    "Maximum health increased by": "最大生命值增加",
    "Meaningless Murky Mix": "无意义的阴暗组合",
    "Mechanical Exoskeleton": "机械外骨骼",
    "Miniature Shurikens": "微型手里剑",
    "Mjolnir": "姆约尼尔",
    "Mounting Dread (Doom) - 5 sec.": "安装恐惧（末日）- 5 秒。",
    "Nature's take on the humble shield.": "大自然对不起眼的盾牌的看法。",
    "Not quite, but it's close!": "不完全是，但已经很接近了！",
    "Not to scale.": "不按比例。",
    "Now featuring step by step guides!": "现在提供分步指南！",
    "Oversized Rat": "超大老鼠",
    "Parka": "派克大衣",
    "Planetary Bulwark": "行星壁垒",
    "Poison Cloud (Bleed) - 15 sec.": "毒云（流血）- 15 秒。",
    "Powerful Hand-Axe": "强力手斧",
    "Pre-Shattered Vial": "预破碎小瓶",
    "Quickblade": "快刀",
    "Raising the stakes, one body at a time.": "提高赌注，一次一个人。",
    "Reinforced Overcoat": "强化大衣",
    "Reinforced Tunic": "强化外衣",
    "Relic of a bygone era.": "过去时代的遗迹。",
    "Repeater": "中继器",
    "Ruthlessness (Armour Shred) - 10 sec.": "无情（护甲撕裂）- 10 秒。",
    "Ruthlessness (Armour Shred) - 15 sec.": "无情（护甲撕裂）- 15 秒。",
    "Sagittarius": "射手座",
    "Sanguine Coagulation": "血色凝结",
    "Serrated for your pleasure": "锯齿状，让您满意",
    "Shoots rainbows and sunshine.": "射出彩虹和阳光。",
    "Should destroy the target's armour, but that would be unbalanced.": "应该摧毁目标的装甲，但这会不平衡。",
    "Shuriken": "手里剑",
    "Slow Burn (Bleed) - 15 sec.": "缓慢燃烧（流血）- 15 秒。",
    "So potent they'll be feeling double as well as seeing it.": "如此强大，他们在看到它的同时也会有双重的感觉。",
    "Spotless Buckler": "一尘不染的圆盾",
    "Spotless Chestplate": "一尘不染的胸甲",
    "Spotless Jerkin": "一尘不染的上衣",
    "Spreading the love.": "传播爱。",
    "Staggered (Paralysis) - 15 sec.": "交错（麻痹）- 15 秒。",
    "Star Searcher": "寻星者",
    "Starfall (Multistrike) - 15 sec.": "星落（多重打击）- 15 秒。",
    "Static Shock (Paralysis) - 15 sec.": "静电冲击（麻痹）- 15 秒。",
    "Steel Cage": "铁笼",
    "Stop! Dapper time!": "停下来！精致的时间！",
    "Stops just about anything that doesn't aim for the head.": "停止任何不瞄准头部的动作。",
    "Storm's Herald": "风暴使者",
    "Straight outta the lake.": "直接从湖里出来。",
    "Strength increased by": "强度增加",
    "Sulphuric Acid Vial": "硫酸瓶",
    "Superior Hand-Cannon": "高级手炮",
    "Superior Slingshot": "高级弹弓",
    "Sword Breaker": "断剑者",
    "Tear Gas Launcher": "催泪瓦斯发射器",
    "Tempered Kilt": "调质短裙",
    "The Ambassador": "大使",
    "The Blue Collar": "蓝领",
    "The Dreamer": "梦想家",
    "The Emperor's Clothes": "皇帝的衣服",
    "The Grim Reaper has arrived.": "死神已经到来。",
    "The Stakeholder": "利益相关者",
    "The Tetranomicon": "四书",
    "They'll probably want it back.": "他们可能会想要回来。",
    "They're not worthy, but you are.": "他们不值得，但你值得。",
    "Threadbare Chestplate": "破旧胸甲",
    "Threadbare Kite Shield": "破旧的风筝盾",
    "Threadbare Tunic": "破旧的外衣",
    "Throw that glass as hard as you can.": "尽你所能地扔那个玻璃杯。",
    "Thundercaller": "雷霆召唤者",
    "Tidehunter's Harpoon": "潮汐猎人的鱼叉",
    "Tome of Flame": "火焰之书",
    "Top Hat and Monocle": "高顶礼帽和单片眼镜",
    "Tranquilized (Sleep) - 15 sec.": "镇定（睡眠）- 15 秒。",
    "Tranquilizer Blowpipe": "镇静剂吹管",
    "Trust me, they're magnificent.": "相信我，他们很棒。",
    "Turtle Shell": "鳖甲",
    "Unbalanced (Paralysis) - 15 sec.": "不平衡（麻痹）- 15 秒。",
    "Usage of a rag is optional.": "抹布的使用是可选的。",
    "Warmaul": "战槌",
    "Weakened Half-Giant": "被削弱的半巨人",
    "What better way to perplex someone than to throw something that does nothing?": "还有什么比扔一些毫无作用的东西更好的方法来迷惑某人呢？",
    "Whatever you do, don't hold it above your head.": "无论你做什么，都不要把它举过头顶。",
    "Why settle for one when you can throw ten?": "当你可以扔十个时，为什么要满足于一个呢？",
    "Wing Clip (Disarm) - 15 sec.": "翼夹（解除武装）- 15 秒。",
    "Wound Poison (Bleed) - 10 sec.": "伤口毒药（流血）- 10 秒。",
    "Wound Poison (Bleed) - 15 sec.": "伤口毒药（流血）- 15 秒。",
    "Written and bound by Tetradigm. Mostly incomprehensible.": "由 Tetradigm 编写和装订。大部分内容难以理解。",
    "Xena's Breastplate": "西娜的胸甲",
    "Yes, dragon is a metal. It's not made of dragons.": "是的，龙是一种金属，它不是由龙制成的。",
    "Yes, this vial contains blood. Drink sparingly.": "是的，这个小瓶里有血液。请少喝。",
    "You gained a Stat Point!": "您获得了属性点！",
    "You know they breathe fire, right?": "你知道他们会喷火，对吧？",
    "You will not go to space today.": "你今天不会去太空。",
    "Your": "你的",
    "Ze Goggles": "泽护目镜",
    "Zey do nothing!": "他们什么也不做！",
    "Frost Orb": "冰霜宝珠",
    "Grimoire": "魔法书",
    "Longblade": "长刃",
    "Robe": "长袍",
    "Scepter": "权杖",
    "Decrepit Javelin": "",
    "You gained a Skill Point!": "你获得了一个技能点！",
    "A successful block has a 5% chance to Disarm the attacker.": "成功阻止有 5% 的机会解除攻击者的武装。",
    "All attacks deal 35% additional damage and cost 1 extra durability.": "所有攻击都会造成 35% 的额外伤害并消耗 1 点额外的耐久度。",
    "Allows debuff timers to be refreshed by reapplying the debuff.": "允许通过重新应用减益来刷新减益计时器。",
    "Applies the Adrenaline Rush effect at the start of combat for 1 strike.": "在战斗开始时施加肾上腺素激增效果，持续 1 次打击。",
    "Armour resistances are converted to vulnerabilities during Burst Attack.": "在爆发攻击期间，装甲抗性会转化为弱点。",
    "Available Skill Points: 1": "可用技能点：1",
    "Broken weapons retain an additional 10% of their effectiveness.": "破损的武器额外保留 10% 的效能。",
    "Burst Attacks have a 20% increased chance to inflict debuffs.": "爆发攻击造成减益效果的几率提高 20%。",
    "Cavity Search": "腔体搜索",
    "Critical strikes do 10% more damage.": "暴击造成的伤害提高 10%。",
    "Critical strikes refresh the cooldown on your Burst Attack.": "暴击会刷新爆发攻击的冷却时间。",
    "100% of blocked damage to your foe after a successful block.": "100% 格挡伤害对敌人，成功格挡后。",
    "2% of damage taken to your foe.": "2% 的伤害对敌人。",
    "Debuffing potions now apply the superior version of their debuff.": "减益药水现在应用其减益的高级版本。",
    "Defensive Skills": "防守技能",
    "Disassembly": "拆卸",
    "Divine Shield now heals you for 20% of the damage that it negated.": "圣盾现在可以治愈你所抵消伤害的 20%。",
    "Divine Shield now reflects 20% of the damage it negated to your foe.": "圣盾现在可以反射它对敌人造成的伤害的 20%。",
    "Each hit has a 5% chance to instantly kill targets below 25% health.": "每次命中有 5% 的几率立即杀死生命值低于 25% 的目标。",
    "Each repair tick restores 20% more durability.": "每修复一次即可恢复 20% 的耐久度。",
    "Five-Finger Discount": "五指折扣",
    "Gain 5% additional experience from combat.": "从战斗中获得 5% 的额外经验。",
    "Grants a 1% chance that your potions will not be consumed upon use.": "有 1% 的几率你的药水在使用时不会被消耗掉。",
    "Grants a 1% chance to gain an additional Skill Point when gaining a skill point from levelling up.": "升级获得技能点时，有 1% 的几率获得额外技能点。",
    "Grants a 1% chance to negate all effects of an attack against you.": "有 1% 的几率抵消对你的攻击的所有效果。",
    "Grants a 1% chance to salvage a piece of scrap from a defeated enemy.": "有 1% 的几率从被击败的敌人身上抢救出一块废料。",
    "Grants a 1% chance to steal seeds equal to your character level when attacking.": "攻击时有 1% 的几率窃取相当于角色等级的种子。",
    "Grants a 2% chance on hit to ignore your foe's armour.": "击中时有 2% 的几率忽略敌人的护甲。",
    "Grants a 2% chance to boost a random stat when levelling up.": "升级时有 2% 的几率提升随机属性。",
    "Grants a 2% chance to deal 50% of damage taken from a hit to your foe.": "有 2% 的几率对敌人造成 50% 的伤害。",
    "Grants a 2% chance to fully repair all equipped items when defeating an enemy.": "击败敌人时有 2% 的几率完全修复所有装备物品。",
    "Grants a 2% chance to gain an additional Stat Point when levelling up.": "升级时有 2% 的几率获得额外的属性点。",
    "Grants a 2% chance to strike again when attacking for 50% damage.": "攻击造成 50% 伤害时，有 2% 的几率再次攻击。",
    "Grants a 2% chance to triple the seed gains from combat.": "有 2% 的几率使战斗中的种子收益增加三倍。",
    "Grants a 3% chance per hit to negate any durability loss.": "每次命中有 3% 的几率抵消任何耐久度损失。",
    "Guarantees an additional piece of scrap from destroying items.": "保证因毁坏物品而获得额外的碎片。",
    "Guarantees the next incoming attack will be blocked after a Shield Crush.": "保证盾牌粉碎后下次传入的攻击将被格挡。",
    "Haggling": "讨价还价",
    "Hanging By A Thread": "不绝如缕",
    "Healing potions restore 10% more of your maximum health.": "治疗药水可以使你的最大生命值恢复 10% 以上。",
    "Heals 5% of your maximum health upon defeating a foe.": "击败敌人后可恢复最大生命值的 5%。",
    "High Maintenance": "维护成本高",
    "Increases experience gain by up to 50% by using up the overflow pool.": "通过耗尽溢出池，将经验增益提高最多 50%。",
    "Increases your inventory size by 4 slots.": "将您的库存大小增加 4 个槽位。",
    "Keen Eye": "敏锐的目光",
    "Keener Eye": "敏锐的目光",
    "Modifies your Burst Attack to deal 50% of normal damage, but strike an additional time.": "修改你的爆发攻击以造成正常伤害的 50%，但会额外攻击一次。",
    "Offensive Skills": "进攻技能",
    "Out of combat, regeneration ticks restore 4% more.": "脱离战斗后，再生蜱恢复 4% 以上。",
    "Reclaimed Wisdom": "重获智慧",
    "Reduces the seed prices in the Store by 3%.": "将商店中的种子价格降低 3%。",
    "Reduces weapon damage taken by 10% when below 30% health.": "当生命值低于 30% 时，受到的武器伤害减少 10%。",
    "Reduces weapon damage taken by 3%.": "受到的武器伤害减少 3%。",
    "Refreshes the cooldown on Burst Attack after a successful dodge.": "成功闪避后刷新爆发攻击的冷却时间。",
    "Removes any active debuffs on you after a Shield Crush.": "盾牌粉碎后移除你身上的所有活跃减益效果。",
    "Restores 6% health when you would otherwise die to an attack, once per battle.": "当你因攻击而死亡时，每场战斗恢复 6% 生命值。",
    "Shortens the cooldown of Burst Attack by 1 second when used against a debuffed foe.": "当对被减益的敌人使用时，爆发攻击的冷却时间缩短 1 秒。",
    "Sneak Attack": "偷袭",
    "Stores overkill damage (up to 20% of target's max HP) and deals it at the start of combat.": "储存过度杀伤（最多为目标最大生命值的 20%）并在战斗开始时造成伤害。",
    "Support Skills": "支持技能",
    "Turn the Tables": "扭转局面",
    "Vengeance": "复仇",
    "Wild Swings": "狂野摇摆",
    "Beanie": "毛线帽",
    "Drain Life (Drain) - 15 sec.": "汲取生命（汲取）- 15 秒。",
    "Emberleaf War Tome": "烬叶战争宝典",
    "Embers are usually bad for books, but not this one.": "余烬通常对书籍有害，但这本书却不然。",
    "Javelin": "标枪",
    "Longbow": "长弓",
    "Shiv": "毒刃",
    "Tights": "紧身裤",
    "Not enough seeds.": "没有足够的种子。",
    "from Reclaimed Knowledge": "来自回收的知识",
    "Gained an additional": "获得了额外的",
    "Musket": "滑膛枪",
    "Trench Coat": "风衣",
    "Broadsword": "大刀",
    "Causes the victim's attacks to be interrupted 15%": "使受害者的攻击被打断15%",
    "Causes the victim's next attack to be directed at themselves. This debuff doesn't have a normal version.": "使受害者的下一次攻击直接针对自己。此减益效果没有普通版本。",
    "Causes you to heal for 20%": "使你恢复 20%",
    "Causes your attacks to deal a second hit for 50%": "使你的攻击造成 50% 的第二次命中",
    "Causes your attacks to ignore the target's armour resistances for 10": "使你的攻击忽略目标的护甲抗性，持续 10",
    "chance to break when the victim is attacked.": "当受害者受到攻击时有机会打破。",
    "chance to instantly die when this debuff expires. If they are not instantly killed, they take 250%": "该debuff结束时有几率立即死亡。如果没有立即死亡，则损失250%",
    "Dagger": "匕首",
    "Generic Melee Weapon": "通用近战武器",
    "Generic Slow (Slow) - 15 sec.": "通用慢速（慢速）- 15 秒。",
    "Halves the victim's damage output and prevents them from applying debuffs for 10": "将受害者的伤害输出减半并阻止他们施加减益效果 10 秒",
    "Hand-Axe": "手斧",
    "Increases damage dealt by weapons by 6%.": "武器造成的伤害提高 6%。",
    "Increases the delay between the victim's attacks by 15%": "使受害者的攻击之间的延迟增加 15%",
    "Machete": "弯刀",
    "Mini-Crossbow": "迷你弩",
    "Modify Debuffs": "修改减益效果",
    "of the main hit's damage for 10": "主击伤害 10",
    "of the time for 10": "的时间为 10",
    "of weapon DPS instead.": "武器DPS代替。",
    "of weapon DPS to the victim every second for 10": "每秒对受害者造成的武器 DPS，持续 10",
    "of your weapon DPS every second for 10": "每秒你的武器 DPS 10",
    "Prevents the victim from attacking for 10": "阻止受害者攻击 10 秒",
    "Random": "随机",
    "seconds, ignoring resistances.": "秒，忽略阻力。",
    "seconds.": "秒。",
    "seconds. Has a 60%": "秒。有 60%",
    "Selects a debuff to apply at random from the above list.": "从上面的列表中随机选择要应用的减益效果。",
    "Spark Orb": "火花宝珠",
    "Tower Shield": "塔盾",
    "Enter the Boss Lair": "进入Boss巢穴",
    "Grubby Loincloth": "脏兮兮的腰布",
    "Hasn't been washed, ever.": "从来没有洗过。",
    "Less words. More pages. Better for bash faces.": "更少的字数。更多页面。更适合暴击脸。",
    "Massive Cave Troll": "巨大的洞穴巨魔",
    "Skull Crack (Confuse) - 5 sec.": "头骨裂缝（混乱）- 5 秒。",
    "Tetranomicon, 2nd Edition": "《四书》，第二版",
    "Tome of Frost": "冰霜之书",
    "Still warm to the touch.": "摸起来还是温暖的。",
    "Blade": "刀刃",
    "Lance": "长矛",
    "Shield": "盾牌",
    "Knife": "刀",
    "Nerve Strike": "神经打击",
    "Kilt": "短裙",
    "Morningstar": "钉头锤",
    "afflicted Massive Cave Troll with Ruthlessness.": "无情地折磨着巨大的洞穴巨魔。",
    "fades...": "淡出……",
    "Ruthlessness": "无情",
    "Skull Crack": "颅骨裂纹",
    "The effect of": "效果对于",
    "You suffer from Skull Crack.": "你受到了 颅骨裂纹 的伤害。",
    "Staff": "杖",
    "Arm Shot": "手臂射击",
    "Whispering Cave cleared!": "低语洞窟 已清理！",
    "Halberd": "长戟",
    "What might appear to be a calm refuge in the wastes, the Whispering Cave soon revealed itself to be anything but that once explorers started to plumb its' depths. The cave plays home to a host of otherwise rare animals that sought sanctuary from the ravaging wars above ground, and the creatures do not take kindly to humans trespassing on one of the few places left for them to call home.": "低语洞窟看似荒野中平静的避难所，但一旦探险者开始探索其深处，它很快就显露了自己的真相。这个洞穴是许多稀有动物的家园，它们在激烈的战争中寻求庇护。在地面上，这些生物并不欢迎人类侵入他们为数不多的可以称为家园的地方之一。",
    "The Ash Cult has long believed the world is overdue to be reborn in flames, and as such has been working around the clock to gather supplies and capture unwitting survivors in the hope of gathering a large enough offering to finally bring the wrath of the heavens down on the world. Small outposts like this one generally don't hold onto their captures for very long, yet if you're lucky there may be some pickings to be had before they're all transported away to their main fortress.": "灰烬教派长期以来一直相信世界早该在火焰中重生，因此一直在夜以继日地收集物资并捕获不知情的幸存者，希望收集到足够多的祭品以最终平息天堂的愤怒像这样的小型前哨站通常不会将捕获的战利品保留很长时间，但如果你幸运的话，在他们全部运往主要堡垒之前可能会得到一些收获。",
    "Also good for piercing... other parts.": "也适合刺穿其他部位。",
    "Ash Cultist Outpost": "灰烬教徒前哨站",
    "Ashen Archmage": "灰烬大法师",
    "Available Zones:": "可用区域：",
    "Cardboard Box": "纸板箱",
    "Chainmail Bikini has been upgraded to level 15": "锁甲比基尼已升级至15级",
    "Ash Cultist Outpost (11 - 20)": "灰烬教徒前哨站 (11 - 20)",
    "Whispering Cave (1 - 10)": "低语洞窟 (1 - 10)",
    "Hypnosis (Sleep) - 15 sec.": "催眠（睡眠）- 15 秒",
    "Hypnotist's Watch": "催眠师的手表",
    "Moved to Ash Cultist Outpost.": "转移到灰烬教徒前哨站。",
    "of Attrition": "消耗",
    "Piercing Throw (Armour Shred) - 15 sec.": "穿刺投掷（破甲）- 15 秒。",
    "Snakes not included.": "不包括蛇。",
    "Throat Piercers": "喉咙穿孔器",
    "Travel to this Zone": "前往该区域",
    "Twinblades": "双刀片",
    "Whispering Cave": "低语洞",
    "You are here!": "你在这里！",
    "Your eyelids are getting heavy...": "你的眼皮越来越重了……",
    "Ashen Spellweaver": "灰烬织法者",
    "\"The Theory of Everything\"": "“万物理论”",
    "Ashen Imp": "灰烬小鬼",
    "Charm (Confuse) - 5 sec.": "魅惑（混乱）- 5 秒。",
    "Comes with a built-in harp, no strings attached.": "配有内置竖琴，无弦。",
    "Expert Strategy (Armour Shred) - 15 sec.": "专家策略（破甲）- 15 秒。",
    "It works! At least, in theory...": "它有效！至少在理论上......",
    "Locked items cannot be sold.": "锁定的物品无法出售。",
    "Throwing Axe": "飞斧",
    "Ashen Recruit": "灰烬新兵",
    "Ashen Engineer": "灰烬工程师",
    "Ashen Summoner": "灰烬召唤者",
    "Ashen Ranger": "灰烬射手",
    "Ashen Warrior": "灰烬战士",
    "You suffer from Nerve Strike.": "你遭受了神经打击。",
    "Sling": "吊带",
    "Fled from the battle.": "从战斗中逃跑了。",
    "Mounting Dread triggers, instantly killing you.": "触发恐惧加剧，立即杀死了你。",
    "You suffer from Mounting Dread.": "你遭受了恐惧加剧。",
    "Comatose": "昏迷",
    "You fall asleep...": "你睡着了...",
    "You suffer from Comatose.": "你遭受了昏迷。",
    "You wake up!": "你醒了！",
    "Flame Orb": "火焰宝珠",
    "Shortsword": "短剑",
    "Helmet": "头盔",
    "Unrealistically heavy.": "沉重得不切实际。",
    "Ash Cultist Outpost cleared!": "灰烬教徒前哨站已清除！",
    "Ashen Berserker": "灰烬狂战士",
    "Bloodrage (Multistrike) - 20 sec.": "血怒（多重打击）- 20 秒。",
    "Definitely not made for walking.": "绝对不适合步行。",
    "Dervish, Hand of Rage": "苦行僧，愤怒之手",
    "Gladius": "剑神",
    "If it had a mouth, it'd be screaming in anger.": "如果它有嘴的话，它一定会愤怒地尖叫。",
    "Iron Boots": "铁靴",
    "Spiked armour has never been a good idea, really.": "尖刺盔甲从来都不是一个好主意，真的。",
    "Spiked Berserker's Mail": "尖刺狂战士锁甲",
    "Greatsword": "巨剑",
    "Moved to Dawn's Light Swamp.": "移至黎明之光沼泽。",
    "Once the site of a mighty battle between warring clans, the area became known as the Dawn's Light Swamp when one side's archmages conjured a massive water wave to overwhelm their foes' defences. While successful, the remaining water seeped into the ground and turned the once lush field into treacherous swampland, which was then promptly taken over by the local wildlife and declared a no-man's land for the remainder of the conflict.": "曾经是交战部族之间激烈战斗的地点，当一方的大法师召唤出巨大的水波来压倒敌人的防御时，该地区被称为黎明之光沼泽。虽然成功了，但剩余的水渗入了地面，使曾经的茂密的田野变成了危险的沼泽地，然后迅速被当地野生动物占领，并在冲突的剩余时间里宣布为无人区。",
    "Tar Globule": "焦油球",
    "Not enough scrap.": "没有足够的废料。",
    "Dazzle": "眩目",
    "Cleaver": "切肉刀",
    "Corrupted Treant": "腐化树人",
    "Hungry Crocodile": "饥饿的鳄鱼",
    "Swamp Piranha": "沼泽食人鱼",
    "afflicted Foul Elemental with Comatose.": "邪恶元素陷入昏迷状态。",
    "afflicted Tar Globule with Comatose.": "受影响的焦油球处于昏迷状态。",
    "Comatose (Sleep) - 0 sec.": "昏迷（睡眠）- 0 秒。",
    "Foul Elemental": "邪恶元素",
    "Foul Elemental falls asleep...": "邪恶元素睡着了……",
    "Rapier": "剑杆",
    "Tar Globule falls asleep...": "焦油球睡着了……",
    "The Foul Elemental wakes up!": "邪恶元素苏醒了！",
    "The Tar Globule wakes up!": "焦油地球苏醒了！",
    "Mud Golem": "泥傀儡",
    "Putrid Slime": "腐烂的史莱姆",
    "Confuse (Confuse) - 5 sec.": "混乱（混乱）- 5 秒。",
    "Domination (Confuse) - 5 sec.": "统治（混乱）- 5 秒。",
    "Rubber gloves are strongly advised.": "强烈建议戴橡胶手套。",
    "Spark-Touched Fetish": "火花触碰的恋物癖",
    "Tell me, tell me everything...": "告诉我，告诉我一切……",
    "Torturer's Poker": "酷刑者的扑克牌",
    "You suffer from Cripple.": "你被削弱了。",
    "Cripple": "削弱",
    "Do it the same, but better.": "做同样的事情，但更好。",
    "Excalibur II": "神剑 II",
    "Holy Radiance (Drain) - 15 sec.": "神圣光辉（汲取）- 15 秒。",
    "Holy Radiance": "神圣光辉",
    "Explosive Shot": "爆炸射击",
    "Decayed Slingshot": "腐烂的弹弓",
    "Dwarven Hand Cannon": "矮人手炮",
    "Dwarves had really large hands.": "矮人的手非常大。",
    "Explosive Shot (Doom) - 5 sec.": "爆炸射击（末日）- 5 秒。",
    "Holy Radiance": "神圣光辉",
    " cleared!": " 已清理！",
    "At least one dragon died in the making of this armour.": "至少有一条龙在制作这件铠甲的过程中死去。",
    "Crushing Blow (Armour Shred) - 20 sec.": "粉碎性打击（护甲撕碎）- 20 秒。",
    "Fermeus, Warmaul of the Wastes": "费缪斯，废土战槌",
    "Runic Platemail": "符文板甲",
    "Sludge-Coated Cloak": "污泥斗篷",
    "Swamp Behemoth": "沼泽巨兽",
    "The slime covering this maul comes from deep within.": "覆盖在这把槌上的粘液来自于它的深处。",
    "Things I don't want to wear today include... this.": "我今天不想穿的东西包括……这个。",
    "Moved to The Final Stop.": "移至终点站。",
    "The Final Stop": "终点站",
    "The Final Stop (31 - 40)": "终点站 (31 - 40)",
    "For many years, the TPX-4450 maglev train ferried thousands of passengers a day across the wastes to go about their daily business. Shortly after the onset of war, a stray blast of arcane magic knocked one of these trains flying off its rail, and the fall of over 100 feet and resulting impact instantly killed everyone on board. With nowhere else to go, the spirits of those slain saw fit to linger in the remains of the train as a warning to any who would approach: only death would find them here.": "多年来，TPX-4450 磁悬浮列车每天运送数千名乘客穿越荒野，处理日常事务。战争爆发后不久，一股奥术魔法的迷失爆炸将其中一列列车从铁轨上撞飞，超过 100 英尺的坠落和由此产生的冲击立即杀死了车上的所有人。由于无处可去，遇难者的灵魂认为适合在火车的残骸中徘徊，向任何接近的人发出警告：只有死亡才能找到他们这里。",
    "Tempered Buckler": "淬炼圆盾",
    "Weapon has been reforged.": "武器已重铸。",
    "Spectral Lady": "幽灵女士",
    "Spectral Child": "幽灵之子",
    "Spectral Businessman": "光谱商人",
    "Disarmed": "解除武装",
    "Judgement Bolt": "审判之箭",
    "Wound Poison": "伤口毒药",
    "- You feel an": "-你感觉",
    "Couldn't carry": "无法携带",
    "Generic Heal (Drain) - 15 sec.": "普通治疗（吸取）- 15 秒。",
    "Generic Magic Weapon": "通用魔法武器",
    "Locked items cannot be scrapped.": "锁定的物品无法废弃。",
    "Overly Elaborate Robe": "过于精致的长袍",
    "Reinforced Hat": "强化帽子",
    "Spectral Businessman": "光谱商人",
    "Spectral Child": "幽灵之子",
    "Spectral Lady": "幽灵女士",
    "Spectral Manager": "频谱管理器",
    "Spectral Passenger": "幽灵旅客",
    "Spectral Tourist": "幽灵游客",
    "subsides.": "平息了。",
    "Tempered Buckler": "淬炼圆盾",
    "Tempered Jerkin": "钢化夹克",
    "Tempered Tights": "钢化裤袜",
    "Tempered Tower Shield": "淬火塔盾",
    "Washing this thing will be your worst nightmare.": "洗这个东西将是你最糟糕的噩梦。",
    "Weapon has been reforged.": "武器已重铸。",
    "You suffer from Disarmed.": "你患有解除武装。",
    "You suffer from Ruthlessness.": "你遭受无情之苦。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "for 10": "for 10",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "EXP: ": "经验值：",
    "Strength (": "力量 (",
    "Intelligence (": "智力 (",
    "Dexterity (": "灵巧 (",
    "Constitution (": "体质 (",
    "Increases chance to block attacks by ": "增加格挡攻击的几率 ",
    "Carried Items ": "携带物品 ",
    "damage ": "伤害 ",
    "Badge earned: ": "获得徽章：",
    "You hit ": "你击中了 ",
    "Generic Player Name (Lv. ": "通用玩家名称（等级 ",
    "Increases chance to block attacks by ": "格挡攻击的几率增加 ",
    "Increases chance to critically strike by ": "暴击率增加 ",
    "Increases chance to dodge attacks by ": "躲避攻击的几率增加 ",
    "Adequate ": "足够的",
    "Average ": "均衡的",
    "Basic ": "基础的",
    "Frayed ": "磨损的",
    "Tattered ": "破烂不堪的",
    "Flawed ": "有瑕疵的",
    "Pristine ": "朴素的",
    "Usable ": "可以使用的",
    "Artemis ": "阿耳特弥斯的",
    "Unremarkable ": "不起眼的",
    "Well-Kept ": "保存完好的",
    "Well-Maintained ": "维护良好的",
    "Passable ": "马马虎虎的",
    "Worthless ": "一文不值的",
    "Simple ": "简单的",
    "Golden ": "镀金的",
    "Powerful ": "强力的",
    "Unimpressive ": "不起眼的",
    "Superior ": "高级的",
    "Polished ": "抛光的",
    "Upgraded ": "升级的",
    "Enhanced ": "强化的",
    "Aegis ": "宙斯盾",
    "Zenith ": "顶峰的",
    "Battleworn ": "久经沙场的",
    "Spotless ": "无瑕的",
    "Threadbare ": "破旧的",
    "Inept ": "笨拙的",
    "Exceptional ": "卓越的",
    "Useless ": "无用的",
    "Cracked ": "有裂纹的",
    "Flamecore ": "火焰核心的",
    "Impressive ": "令人印象深刻的",
    "War ": "战争之",
    "Heavy ": "厚重的",
    "Damaged ": "损坏的",
    "Decrepit ": "破旧的",
    "Level up! You are now level ": "升级了！您现在达到了等级 ",
    "Available Skill Points: ": "可用技能点数：",
    "Increases armour bonuses by ": "护甲加值增加 ",
    "Increases attack speed by ": "攻击速度提高 ",
    "Increases chance to block by ": "格挡几率增加 ",   
    "Increases critical strike chance by ": "暴击率提高 ",
    "Increases damage dealt by weapons by ": "武器造成的伤害提高 ",
    "Increases seed gains from combat by ": "战斗中获得的种子数量增加 ",
    "Increases seeds received from selling items by ": "出售物品获得的种子增加 ",
    "Increases the chance of gaining a potion at the end of combat by ": "战斗结束时获得药水的几率增加 ",
    "Increases the chance of striking first when starting combat by ": "战斗开始时先发制人的几率提高 ",
    "Increases the chance to apply your weapon's debuff by ": "使武器施加减益效果的几率提高 ",
    "Increases the damage dealt by Flurry's secondary strike by ": "乱舞的二次攻击造成的伤害增加 ",
    "The victim has a ": "受害者有一个 ",
    "Deals ": "造成 ",
    "Normal (": "普通 (",
    "prevented ": "阻止了 ",
    "healed you for ": "治疗了你",
    "Current Zone: ": "当前区域：",
    "Dawn's Light Swamp": "黎明之光沼泽",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    " hits you with their": " 攻击了你通过使用它们的",
    " with your": " 通过你的",
    " suffers from Drain Life.": " 遭受了“汲取生命”之苦。",
    " scrap)": " 废料)",
    " suffers from Static Shock.": " 遭受了“静电冲击”之苦。",
    " suffers from Nerve Strike.": " 遭受了“神经打击”之苦。",
    " from attacking.": " 的攻击。",
    " hits you with their fists for": "用拳头攻击你造成了 ",
    " suffers from Arm Shot.": " 遭受了“手臂射击”之苦。",
    " suffers from Dazzle.": " 遭受了“眩目”之苦。",
    " suffers from Cripple.": " 遭受了“瘫痪”之苦。",
    " suffers from Wound Poison.": " 遭受了“伤口毒药”之苦。",
    " suffers from Explosive Shot.": "遭受了“爆炸射击”之苦。",
    " suffers from Holy Radiance.": " 遭受了“神圣光辉”之苦。",
    " suffers from Judgement Bolt.": " 遭受了“审判之箭”之苦。",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+) DPS\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^等级(.+)$/,
    /^购买(.+)$/,
    /^伤害(.+)$/,
    /^暴击(.+)$/,
    /^格挡(.+)$/,
    /^经验(.+)$/,
    /^生命(.+)$/,
    /^灰烬(.+)$/,
    /^躲避(.+)$/,
    /^获得(.+)$/,
    /^速度(.+)$/,
    /^成本(.+)$/,
    /^(.+)耐久$/,
    /^(.+)远程$/,
    /^(.+)近战$/,
    /^(.+)魔法$/,
    /^\(([\d\.]+) \/ ([\d\.]+)\)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.,]+) \- ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^The next three attacks after a critical strike deal (.+) more damage.$/, '暴击后接下来的 3 次攻击造成的伤害提高 $1。'],
    [/^(.+) triggers, dealing (.+) damage to the (.+).$/, '触发 $1，对 $3 造成 $2 点伤害。'],
    [/^(.+) with your fists for (.+) damage.$/, '$1 用拳头对你造成 $2 点伤害。'],
    [/^(.+) with your fists for (.+) damage! \(Critical\)$/, '$1 用拳头对你造成 $2 点伤害！（暴击）'],
    [/^(.+) has been upgraded to level (.+)$/, '$1 已升级至 $2 级'],
    [/^(.+) suffered (.+) additional damage from (.+).$/, '$1 受到来自 $3 的额外 $2 点伤害。'],
    [/^You restored (.+) health from (.+).$/, '您通过 $2 恢复了 $1 生命值。'],
    [/^Skull Crack \((.+) sec\)$/, '颅骨裂纹（$1 秒）'],
    [/^Arm Shot \((.+) sec\)$/, '手臂射击（$1 秒）'],
    [/^Mounting Dread \((.+) sec\)$/, '恐惧加剧（$1 秒）'],
    [/^Explosive Shot \((.+) sec\)$/, '爆炸射击（$1 秒）'],
    [/^Wound Poison \((.+) sec\)$/, '伤口毒药（$1 秒）'],
    [/^Judgement Bolt \((.+) sec\)$/, '审判之箭（$1 秒）'],
    [/^Disarmed \((.+) sec\)$/, '解除武装（$1 秒）'],
    [/^Dazzle \((.+) sec\)$/, '炫目（$1 秒）'],
    [/^Cripple \((.+) sec\)$/, '削弱（$1 秒）'],
    [/^Holy Radiance \((.+) sec\)$/, '神圣光辉（$1 秒）'],
    [/^Ruthlessness \((.+) sec\)$/, '无情（$1 秒）'],
    [/^Comatose \((.+) sec\)$/, '昏迷（$1 秒）'],
    [/^Static Shock \((.+) sec\)$/, '静电冲击（$1 秒）'],
    [/^Nerve Strike \((.+) sec\)$/, '神经打击（$1 秒）'],
    [/^Drain Life \((.+) sec\)$/, '吸血（$1 秒）'],
    [/^Purchased (.+) for (.+) seeds.$/, '购买了 $1 花费了 $2 种子。'],
    [/^Gives a (.+) to restore (.+) HP when attacking.$/, '攻击时有 $1 几率恢复 $2 点生命值。'],
    // [/^You hit (.+) with your$/, '你击中了 $1 通过你的'],
    // [/^(.+) hits you with their$/, '$1 攻击了你通过使用它们的'],
    [/^causes you to attack yourself for (.+) damage.$/, '使你攻击了自己，造成 $1 点伤害。'],
    [/^(.+) Level: (.+) seeds$/, '\$1 等级: $2 种子'],
    [/^Not enough scrap to reset stat points \- (.+) required.$/, '没有足够的废料来重置属性点 \- 需要 $1。'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^Speed ([\d\.]+)$/, '速度 $1'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) point free$/, '$1 免费点数'],
    [/^([\d\.,]+) points free$/, '$1 免费点数'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) doses$/, '$1 剂量'],
    [/^([\d\.,]+) uses$/, '$1 耐久'],
    [/^for ([\d\.,]+) seeds.$/, '$1 种子。'],
    [/^and received ([\d\.,]+) scrap.$/, '并获得了 $1 废料。'],
    [/^HP: (.+) \/ (.+) \((.+)\)$/, '生命值: $1 \/ $2 \($3\)'],
    [/^\+([\d\.,]+) point$/, '\+$1 点数'],
    [/^\+([\d\.,]+) Ranged$/, '\+$1 远程'],
    [/^\+([\d\.,]+) Magic$/, '\+$1 魔法'],
    [/^\+([\d\.,]+) Melee$/, '\+$1 近战'],
    [/^\-([\d\.,]+) Melee$/, '\-$1 近战'],
    [/^\-([\d\.,]+) point$/, '\-$1 点数'],
    [/^\-([\d\.,]+) Ranged$/, '\-$1 远程'],
    [/^\-([\d\.,]+) Magic$/, '\-$1 魔法'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Quality Up: (.+) scrap$/, '质量提升：$1 废料'],
    [/^Purchase: (.+) seeds$/, '购买：$1 种子'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);